### ISSUE TITLE
Enable base map mode

### ISSUE THREAD

**Issue by TimJMartin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#111]
Hi

We currently create vector mbtiles using Mapbox Studio Classic or tippcanoe and I have tried to use them with the plugin but it does not seem to work as expected.

In one of my MBTiles I have a 30 layers ranging from Z6 to Z15 and when I add it the data for the current extent is shown. However when I pan and move I am getting a number of stack errors and reading the docs I have to go to Vector> Vector Tile Reader > Load Features Overlapping.....

i saw this https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/82 but how to I activate it so when i zoom or pan the data is refreshed?

thanks

**Comment by mnboos** [comment]
Hi

This feature is enabled, if you choose "Zoom > Auto (scale based)". The tiles are then automatically reloaded according to the zoom level that is derived from the current map scale.

**Comment by TimJMartin** [comment]
Doesn't seem to be working for my MBTiles then.

I have ticked the Auto (scale based) when I connected to the source file.

The data loads initially and then when I pan or zoom out or zoom in this is the result:

<img width="1680" alt="screen shot 2017-10-30 at 20 18 48" src="https://user-images.githubusercontent.com/8383616/32193596-b3e1eeac-bdaf-11e7-9803-b9cb4fa025ca.png">

You can see the data has not been refreshed. I am also getting many errors, they all seem to be the same message.

Is my data missing something?

`2017-10-30T20:23:15	1	Traceback (most recent call last):
			  File "/Users/tjmartin/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 886, in _on_timeout
			    should_notify = self._predicate()
			  File "/Users/tjmartin/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 200, in _have_extent_or_scale_changed
			    has_extent_changed = self._has_extent_changed()[0]
			  File "/Users/tjmartin/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 237, in _has_extent_changed
			    new_extent = clamp_bounds(new_extent, bounds)
			  File "/Users/tjmartin/.qgis2/python/plugins/vector_tiles_reader/tile_helper.py", line 43, in clamp_bounds
			    x_min = clamp(bounds_to_clamp["x_min"], low=clamp_values["x_min"])
			TypeError: 'NoneType' object has no attribute '__getitem__'
			
2017-10-30T20:23:19	1	Traceback (most recent call last):
			  File "/Users/tjmartin/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 886, in _on_timeout
			    should_notify = self._predicate()
			  File "/Users/tjmartin/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 200, in _have_extent_or_scale_changed
			    has_extent_changed = self._has_extent_changed()[0]
			  File "/Users/tjmartin/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 237, in _has_extent_changed
			    new_extent = clamp_bounds(new_extent, bounds)
			  File "/Users/tjmartin/.qgis2/python/plugins/vector_tiles_reader/tile_helper.py", line 43, in clamp_bounds
			    x_min = clamp(bounds_to_clamp["x_min"], low=clamp_values["x_min"])
			TypeError: 'NoneType' object has no attribute '__getitem__'`

**Comment by mnboos** [comment]
Could you show me the metadata of your mbtiles? Or even better, could you give me your mbtiles file?

**Comment by TimJMartin** [comment]
This isn't the full one as thats over 2Gb, but the same thing seems to happen to this one that just contains contour lines.

https://www.dropbox.com/s/lzb1ovk8hrel6vp/test.mbtiles?dl=0

I am thinking my MBTiles does not contain enough metadata, as mentioned above this was created using Mapbox Studio Classic.

**Comment by mnboos** [comment]
![image](https://user-images.githubusercontent.com/22575883/32194244-1fe540ae-bdba-11e7-84e3-53b89fdc6c1e.png)

Bounds seemts to be missing in the metadata. That's interesting, because I thought to handle that case properly. Obviously not. I will fix that.

@sfkeller That's somehow funny, as we just today discussed, that this should be allowed, especially for mbtiles files, where the bounds theoretically could be derived from the data.

**Comment by TimJMartin** [comment]
hmmmmmmm

Just looking at Classic there doesn't seem to be a way for me to make sure the metadata is added to the MBTiles.

Do you have a list of the mandatory metadata fields?

**Comment by mnboos** [comment]
I would say the following:

- crs (if it's missing, my plugins assumes 3857, so that could still work)
- min zoom
- max zoom
- bounds

You could take any sqlite browser and open the mbtiles file (it's just a sqlite database with a changed file extension. There you could have a look at the metadata table).
I just did this, bounds are missing:

![image](https://user-images.githubusercontent.com/22575883/32194876-eabedea6-bdbb-11e7-900a-ea0cbf64d1c3.png)

**Comment by mnboos** [comment]
I don't know the mbtile generators very well, but I think there must somehow be an option where you can specify the bounds, or generally metadata, if it's not set automatically.

**Comment by TimJMartin** [comment]
I got it working, many thanks for your help

Bounds is in WGS84 coordinates and as you say can easily be added using something like DB Browser for SQLite.

**Comment by mnboos** [comment]
Glad I could help. :-) Have fun!
