### ISSUE TITLE
Default tile servers only result in water layer

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#115]
I connect to Mapzen.com, select all layers, click "Base Map Defaults", and Add. I get all the layer groups, but only water has a layer within - all the others are empty.

**Comment by tomchadwin** [comment]
Ditto OpenMapTiles.com - only water.

**Comment by mnboos** [comment]
I assume that happens after a fresh QGIS start, where the location is not set yet?

**Comment by tomchadwin** [comment]
Apologies, but I think this might be my misunderstanding how it works. Do individual QGIS layers appear and disappear in the layer groups according to what is visible on the canvas and at the zoom level?

**Comment by mnboos** [comment]
Yes. At least the are added as soon as data for an according layer is added the first time. After that, only the source of the layer will be updated. If a layer has a source without features, a specific icon is shown: ![image](https://user-images.githubusercontent.com/22575883/32567829-c7a0e920-c4bc-11e7-8884-7711eca3b47d.png)

**Comment by tomchadwin** [comment]
OK, I'll assume I misunderstood, and close this. Apologies.

**Comment by mnboos** [comment]
Nothing to apologize Tom! It's awesome you're always testing and trying out things.  👍
