### ISSUE TITLE
Are the layer groups required?

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#116]
Basing this question only on the `sample_data`, the ToC structure seems to be every layer within a layer group. Is it always one layer per group? If so, why bother with the groups at all?

**Comment by mnboos** [comment]
There can be up to three layers per group. One per geo type (point, linestring, polygon).

**Comment by tomchadwin** [comment]
OK, thanks for clarifying.
