### ISSUE TITLE
API stability/semantic versioning

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#123]
I was calling TileJSON as follows:

```python
from vector_tiles_reader.tile_json import TileJSON
json = TileJSON(json_url)
json.load()
```

This worked until I upgraded VTR this morning. I see that it is now `vector_tiles_reader.util.tile_json` in the new version. I know you are not advertising a public API, but it would be useful if it could be stable, or if you used semantic versioning.

**Comment by mnboos** [comment]
Ah sorry, you're totally right. My mistake!
