### ISSUE TITLE
Project background colour

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#125]
I think the plugin sets your project background colour. I don't think it should, at least not without an optional GUI setting.

**Comment by mnboos** [comment]
It does only, when the default OpenMapTiles styling checkbox is checked.

**Comment by tomchadwin** [comment]
I still think it's not a setting which should be changed without explicitly notifying the user.

**Comment by sfkeller** [comment]
Interesting issue: "Background color" in fact is a project property, currently set by this plugin without notice when OpenMapTiles styling checkbox is checked. This is a need from some VT styles.
 
This situation is somehow comparable to CRS where some sources set or override the project CRS to 3857 and enable OTF - like some WMTS which are only in 3857 - and like MVT!

We have to thoroughly think about again how this plugin should behave regarding both project settings, background color and CRS.

**Comment by tomchadwin** [comment]
I'm not sure it's the same with CRS. The project CRS changes to match the opened layer only if the layer is the first to be added to the project, right?

I just think a checkbox in the plugin dialogis needed to say "Set project background colour from vector tile style" or something line that.

**Comment by mnboos** [comment]
I think applying a style but not its background colour doesn't make sense.

**Comment by sfkeller** [comment]
Wait a moment; you can't state this in general. Regarding styling there are at least three choices about background colour: 1. assume default (white), 2. don't care (like in raster), 3. set or overwrite background.

**Comment by tomchadwin** [comment]
If I consciously set my own bg colour, I have a reasonable expectation not to have that colour overwritten silently when opening a layer. I don't imagine any other provider would do it, though obviously I'm aware that layers/providers are generally separated from styles.

Think of it as a separation issue: adding a layer is a separate concern to changing project settings. My project might well already have many other layers and a specifically chosen bg colour.

**Comment by sfkeller** [comment]
I see your points. Just consider following: 
* This VT plugin currently only sets bg colour when a specific style is chosen by the user and/or VT source (currently it's the "Apply predefined OpenMapTiles style"). 
* When designing a basemap style you always have to decide on how to deal with map bg (or paper color).
* When the user chooses a raster source as basemap, it's likely having it's own bg colour anyway since raster is likely to be opaque.

So actually, we have a new situation with VT here and we have to think out-of-the-box (which makes VT such an awesome new technology to me...).

**Comment by tomchadwin** [comment]
Point by point:

- "style" in QGIS would mean layer style to a significant majority of users

- sure - make it a checkbox

- that is not a background colour, but part of the layer

I really think you should consider the inside of the box on this. Other than the fact that it's more work, why do you object to giving more control to the user without losing any functionality?

**Comment by sfkeller** [comment]
I'm not objecting ultimately, I'm just pondering :-)

**Comment by sfkeller** [comment]
@klokan / @nvkelso : Do you know if all "web" VT styles you know (MB GL JS or Tangram) use and set background color explicitly?

Setting the background color in a GIS is part of the "map project" settings as @tomchadwin points out and he suggests to offer an option "Set project background color from style" or similar. 

I found "background-color" in MB GL style specs. TileJSON obviously does not contain this in its metadata currently: https://github.com/mapbox/tilejson-spec/issues/9 )

**Comment by sfkeller** [comment]
I've got no feedback so far but came to following conclusion: I checked Maputnik and assume MB Studio is similar: Both show the background color settings at the top. In a map style - especially if it's a base map - background color is an integral part of the design. Soon, there will be an option in the "Add Vector Tile Layer" dialog to attach a MB G JS style file to a VT source. 

My proposal is: If an attached style contains "background-color" attribute, this project setting will be overwritten followed by an info/warning message (and log entry) saying "Style '{style-name}' has changed project property 'background color'."

**Comment by tomchadwin** [comment]
I'll have one last go at trying to persuade you not to do this:

- you should *never* do something the user is not expecting
- you should *never* do something which the user cannot easily undo
- a VT layer is still a layer, and therefore *all actions relating to that layer should affect only that layer*
- the parallel of rasters is not valid - they don't have a background, but have pixels there, ie data, ie part of the layer
- other vector layer sources *never* change the project background, even if they are eg country outlines which would benefit from a sea colour

I guess the other thing I'm concerned about is that this *seems* as though you think, if people use VTR in QGIS, the VT layer will be the only thing of importance in their project. In fact, a VTR could be just one of many aspects of a QGIS project. None of those aspects should bleed into any other.

If this hasn't persuaded you simply to make this a checkbox in the VTR dialog (default checked, if you want, that's no problem), and you are only going to notify via the log, **please log the old colour you are replacing** so that a user can easily revert the damage you've done to their project without their explicit permission.

**Comment by sfkeller** [comment]
Persuaded! (Fun side remark: VT reminds me to video terminal, and VTR to video tape recorder... so I think we should say "MBVT Reader" :-).

@mnboos : I suggest now following:
  * In the "Add Vector Layer..." dialog, add next to "Apply Style" a checkbox "Overwrite background color" (default checked), 
 * notify user displaying "Style '{style-name}' has changed background color (see log).", and 
 * notify in log "Style '{style-name}' changed background color from {old-value} to {new-value}".

**Comment by tomchadwin** [comment]
I hope you don't feel bullied... But thanks!

**Comment by nvkelso** [comment]
@tomchadwin In Tangram it's https://mapzen.com/documentation/tangram/scene/#background.

**Comment by mnboos** [comment]
Summary:
- Checkbox for enable / disable overwrite of project background color
- As a result of the style generator, the Checkbox "Aply predefined OpenMapTilesStyle" naming is not correct anymore and should be renamed to something like "Apply GL JSON Style"

**Comment by mnboos** [comment]
Done
