### ISSUE TITLE
Scale-dependent layer visibility

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#126]
Am I right in thinking that the plugin adds and removes layers completely from the layers list as they become visible or hidden at different zoom levels? If so, would it not be better to give them QGIS scale-dependent visibility instead:

- easier to style layers as they don't need to be visible at the canvas's current zoom level to be present in the layers list and hence accessible to style

- offloads showing and hiding layers to native QGIS functionality

- simplifies and reduces plugin codebase

**Comment by sfkeller** [comment]
Yes, you're right. Every zoom level really has a potentially different schema with potentially different (simplified) geometries. E.g. some vector tile providers replace the landuse/landcover from OSM on detailed zoom level to the more generalized Natural Earth data on zoom levels up to 1.

**Comment by tomchadwin** [comment]
Ah, so it doesn't just show or hide a given layer - it replaces layers with others?

I have an ulterior motive for this, of course: for qgis2web to reexport styled VT groups imported via VTR, a problem I am having is that some layers are not present in the project at any given zoom level, meaning they are missed out from the export.

**Comment by mnboos** [comment]
Once a layer has been added, it stays in the project, but its datasource will be updated.

**Comment by sfkeller** [comment]
@mnboos Can you describe once again the rules how the 1. main group name entry, 2. the layer group entries and 3. the layer names are derived from the VT source/metadata, and 4. how these are changed when zooming in/out (or point to some docs)?

**Comment by sfkeller** [comment]
@tomchadwin Many thanks for your testing and contributions of this MVT reader! Just a remark little bit offtopic regarding qgis2web: IMHO as qgis2web I would only reexport VT sources which are not remote (like e.g. mbtiles). All remote services should be exported as "normal" Leaflet VT sources - very much like WMS.

**Comment by tomchadwin** [comment]
@sfkeller If I understand you correctly, that is indeed what qgis2web does with VT layers from Vector Tiles Reader. It simply graps the source URL and includes it in a Leaflet map. The added value, though, is the styling. qgis2web exports the QGIS styles as Leaflet.VectorGrid or OpenLayers styles. This means that there is now a QGIS workflow for applying your own styles to a third-party VT server Does that make sense?

I've not looked at local mbtiles VT sources from VTR, as they have much less relevance to webmaps. In fact, I'm probably not even detecting when a VTR source is a server, so I need to add that in.

**Comment by tomchadwin** [comment]
> Once a layer has been added, it stays in the project, but its datasource will be updated.

Is the change in the datasource limited to the layer being requested? Otherwise the source remains the same, right? And you confirm that layers are never dynamically *removed* as they disappear from the QGIS canvas?

Having thought about this more, I see that my original request is not possible: you cannot initially populate the tree with all layers from all possible zoom layers and all extents, because the initial request to the VT source only brings back the layers in the viewport.

So, a less violent change to the workflow, but which I still think would work better is:

1. Add VT layer
2. VTR brings in the layers currently visible at the canvas extent/zoom
3. **Set QGIS scale-dependent visibility on individual layers**
4. VTR dynamically adds more layers as they become visible
5. **Continue to set the scale-dependent visibility on these dynamically added layers**

Only 3 and 5 are possibly not already done by VTR.

The workflow for custom QGIS styling and then reexport to a webmap via qgis2web would therefore be: pan and zoom around until you believe all possible layers have been dynamically imported.

I hope it's clear what I am trying to achieve here: the ability to style a remote VT source using QGIS's amazing styling tools, then create a webmap using that VT source and those QGIS styles.

**Comment by mnboos** [comment]
I don't see why point 3 and 5 would be necessary. If for a given zoom and extent no features are loaded, the layer source, which is GeoJSON, will have an empty 'FeatureCollection'. As a result of this, the layer stays in the tree, but no features are actually shown, as there are none for this layer.

> Is the change in the datasource limited to the layer being requested? Otherwise the source remains the same, right? And you confirm that layers are never dynamically *removed* as they disappear from the QGIS canvas?

In reality, most of the layer-sources will always be updated and end up with new features or without any features. Exceptional situations are for example if you see only water and nothing else.

**Comment by tomchadwin** [comment]
I was wondering that as I typed that previous message. Question: is one layer within a subgroup ever replaced by another of the same name and geometry type? If not, perhaps everything is fine.

**Comment by mnboos** [comment]
No. Once a layer is in the tree, it stays there, even if its feature collection is empty. This means, a layer group can end up with at most 3 layers (1x polygon, 1x point, 1x linestring). These layers will have the same name, actually the same name as the group they're placed in.

**Comment by tomchadwin** [comment]
I think that you are correct, and no change is therefore required. Thanks for your patience as I talked this through.

**Comment by mnboos** [comment]
Happy to help :-)
