### ISSUE TITLE
VT data sources from projections other than web mercator

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#127]
add ability to read from VT data sources which have projections other than web mercator.

**Comment by mnboos** [comment]
@sfkeller Do you mean for example Swiss OMT (https://openmaptiles.com/coordinate-systems/)?

**Comment by sfkeller** [comment]
Yes.

**Comment by mnboos** [comment]
Okay, thats included in todays release v1.3.0.

**Comment by sfkeller** [comment]
If you have unit or blackbox tests and (documented) examples for that nice feaure, you can close this issue.
