### ISSUE TITLE
Add Layer dialog does not resize

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#128]
Given a screen with 900 and less pixels, do an "Add Vector Tiles Layer...", modal dialog opens. 
(Do some stuff with other sources like WMS I can't remember... :-()
Then the dialog is so high that buttons at bottom of dialog can't be reached. 
Any attempt of resizing the dialog fail - it switches back.
Seems like the layers list is'nt made scrollable.

**Comment by mnboos** [comment]
IMHO it's nowadys rather unusual to have a display with such a low resolution. The connections dialog was developed for at least FullHD.

The layer list is scrollable:
![image](https://user-images.githubusercontent.com/22575883/32980248-250812a2-cc63-11e7-89e0-43f8a0cd8afd.png)

**Comment by sfkeller** [comment]
Tablets still have this low resolution and I think we should not exclude these.
I'll come back on this issue when I manage to replicate the behaviour where the list was not scrollable.

**Comment by mnboos** [comment]
QGIS on a tablet?

**Comment by sfkeller** [comment]
Yes, (Rugged) Windows tablet: 
![grafik](https://user-images.githubusercontent.com/43340/32983069-30d36376-cc8f-11e7-8e3f-80ecdff44a35.png)

**Comment by mnboos** [comment]
What's the resolution of the tablet?

**Comment by mnboos** [comment]
Fixed. Resizes automatically if required. Minimum height is about 550px, that's the minimum required for the connections dialog to show all options.
