### ISSUE TITLE
Performance issues with rule-based style and expression functions

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#133]
The MB GL style generator - as currently implemented here by #87 - generates QML containing rule-based style and expression functions. 

Now it seems that there are performance issues when using theses styles. My guess is, that the evaluation of expressions currently is especially slow due to it's current implementation in QGIS (QgsExpression parser+evaluator).

@mnboos Can you provide some more details how to reproduce this slow behaviour? Perhaps some rudimentary logging ("profiling") would also be helpful. Or could you already resolve this issue?

**Comment by mnboos** [comment]
It's not that bad anymore. I think I can make some more improvements.

**Comment by mnboos** [comment]
Actually, it strongly depends on the style and there is room for improvement.
