### ISSUE TITLE
MB GL JS pixels do not correspond to QGIS and other pixels

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#136]
When mapping MB GL JS to QGIS styles (#87) there seems to be a glitch regarding pixels values. If these pixel values are mapped 1:1 to QGIS pixels, the resulting graphic size in QGIS seems to be much larger.

The MB GL JS  spec speaks of "Units in pixels", e.g. line-width (https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-line ). Now, there is evidence that this is a special kind of pixel units....

Perhaps this could help? https://gis.stackexchange.com/questions/259407/style-line-width-proportionally-to-maintain-relative-size-in-mapbox-gl 

Else I'd suggest to open an issue in https://github.com/mapbox/mapbox-gl-js/issues .

**Comment by mnboos** [comment]
This may also be helpful: https://github.com/mapbox/mapbox-gl-js/blob/3f419f30b99271cf05c269c8cd40d5c948119533/src/style-spec/expression/definitions/interpolate.js#L213

**Comment by tomchadwin** [comment]
This isn't a DPI/HiDPI issue is it?

**Comment by mnboos** [comment]
I think it's a scaling issue, resulting from my mapping "map_scale -> zoom", which seems to differ from Mapbox.

**Comment by mnboos** [comment]
Finally:

![image](https://user-images.githubusercontent.com/22575883/33204082-9a06e404-d102-11e7-892a-1b24135d1ffa.png)
