### ISSUE TITLE
Permission issues reading SVGs

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#138]
I can't quite understand what the issue is yet, so a simple question to begin with: how are the SVG marker symbols created, and where are the SVGs saved? I'm getting a permission error when trying to work with them.

**Comment by mnboos** [comment]
The icons are located in the /styles/icons folder, which is then added to the QGIS svg lookup directories. Have you got a stacktrace or so?

**Comment by tomchadwin** [comment]
The error happens in qgis2web, so I'll raise the issue in the MBVT thread and tag you. Thanks.
