### ISSUE TITLE
OpenMapTiles style: waterways too wide?

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#139]
![waterways](https://user-images.githubusercontent.com/7840213/33229399-e0123a16-d1c5-11e7-9328-4b52a70911e9.png)

**Comment by mnboos** [comment]
Correct. However, this style will soon be replaced by the mapbox2qgis style generator, which produces more correct results.

**Comment by tomchadwin** [comment]
Thanks.
