### ISSUE TITLE
QGIS Layer Styling panel: empty layer selector dropdown

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#141]
MBVT layers don't seem to appear in the layer selector dropdown at the top of the Layer Styling panel. This screenshot is with the OpenMapTiles layer 'boundary' selected in the QGIS layers list:

![styling](https://user-images.githubusercontent.com/7840213/33230379-68d7855e-d1da-11e7-99ca-a437285c4df6.png)

**Comment by sfkeller** [comment]
Can confirm that here on latest develop branch. It's weird though and not really a bug since styling in Layer Properties looks alright.

@mnboos:
 * Seems like they added another field in the API when they introduced the Layer Styling panel?
 * Could be a field is missing which identifies the layer/group name?

**Comment by tomchadwin** [comment]
Just to confirm that there don't seem to be any other effects of this. But it is odd, and I'd be a little concerned in case some other side effect later becomes apparent.

**Comment by mnboos** [comment]
I'm investigating, but it's difficult to find out where / how to start. I assume it has to do with how I add the layers to QGIS. If I add a vector layer with the same source manually via QGIS, it appears in the styling panel.

**Comment by mnboos** [comment]
Maybe @m-kuhn can give me a hint where to have a look at?

**Comment by m-kuhn** [comment]
How do you add the layer?

**Comment by mnboos** [comment]
```python
QgsMapLayerRegistry.instance().addMapLayers(layers, addToLegend=False)
```

And then add them to layer tree groups.

**Comment by m-kuhn** [comment]
What's the `False` for?

**Comment by sfkeller** [comment]
> What's the False for?

addToLegend according to http://geoapis.sourcepole.com/qgispyapi/qgsmaplayerregistry#QgsMapLayerRegistry.addMapLayers .

BTW: Funny when a C++ programmer asks a Python programmer about a Python method given it is a wrapper around a C++ method / API :-)

**Comment by mnboos** [comment]
```python
QgsMapLayerRegistry.instance().addMapLayers(layers, addToLegend=False)
```

However, it doesn't even make a difference if ```addToLegend``` is ```True``` or ```False```.

**Comment by m-kuhn** [comment]
AFAIK, the combobox listens for the `QgsMapLayerRegistry.layersAdded` signal. Can you verify if this is actually emitted?

> BTW: Funny when a C++ programmer asks a Python programmer about a Python method given it is a wrapper around a C++ method / API :-)

Apparently, @mnboos understood the aim of the question very well ;-)

**Comment by sfkeller** [comment]
You got me! Just another humble hint: QuickMapServices also seems to use `false`, and it appears in the combobox from what I see: https://github.com/nextgis/quickmapservices/blob/master/src/qgis_map_helpers.py#L149 . It's actually followed by a `insertLayer(position, layer)` at next line 150...

**Comment by mnboos** [comment]
The signal ```QgsMapLayerRegistry.layersAdded``` is correctly emitted.

**Comment by m-kuhn** [comment]
What's in `layer.name()`?

**Comment by mnboos** [comment]
The names of all the layers that were added:

```names: [u'water_name', u'building', u'water', u'transportation', u'landcover', u'boundary', u'transportation', u'place', u'building', u'transportation_name', u'landuse', u'building', u'waterway', u'housenumber', u'poi', u'water_name']```

**Comment by sfkeller** [comment]
I see same entry (e.g. building) 3 times in the list...?!

**Comment by mnboos** [comment]
Because there are multiple layers with the same name (but different geo type).

**Comment by m-kuhn** [comment]
Can you provide a minimal code sample to reproduce this behavior?

**Comment by sfkeller** [comment]
I also would suggest to see what happens when a layer is added "manually" via QGIS Python Console.

**Comment by mnboos** [comment]
Closed, because this can currently not be solved.
