### ISSUE TITLE
Attribution to the data sources

### ISSUE THREAD

**Issue by klokan** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#145]
OpenStreetMap data and OpenMapTiles require attribution whenever the map is displayed.

There may be an easy way how to do that in QGIS on screen:

From https://gis.stackexchange.com/questions/126737/how-to-insert-a-statement-e-g-copyright-which-remains-visible-in-mapping-wind

> There's a "Copyright" decoration option in QGIS already.
> > View... Decorations... Copyright Label.

The plugin could probably enable this decoration and directly set the text from the "attribution" field provided in the TileJSON of the source. This field is used for attribution in OpenLayers and in Mapbox too. HTML text seems to be supported on QGIS side.

This way the OpenStreetMap attribution would be visible on the screen by default, and if the user is extremely bothered he/she can still disable it.

It is not ideal - as attribution does not appear in printed maps and the links cannot be clicked - but it would be a good beginning...

**Comment by tomchadwin** [comment]
Attributions can also be set per-layer, but I'm not sure about layer groups. Setting the attribution on the root layer group would be ideal.

**Comment by sfkeller** [comment]
I'm very much in favor of attribution. But in this case I'm reluctant to let the plugin create a Copyright decorator. I propose to rather put this forward as a default decorator in the print composer (or e.g. qgis2web?). QGIS 3 is in early stages and chances are high that pull requests are accepted. 

Reason is that it's about decorators like a legend which - as you say too - have to go to the QGIS project settings, and/or even more typical to the print composer. 

In fact, each layer properties has already set the Attribution title and URL:

![grafik](https://user-images.githubusercontent.com/43340/33239319-a2952f74-d29f-11e7-80d3-072ad3fa12dc.png)

**Comment by sfkeller** [comment]
Can I close this (as Milestone 2 is approaching...)? Can reopen at any time.

**Comment by tomchadwin** [comment]
If qgis2web is not outputting those layer attributions, that's an error, so I'll look into it.

**Comment by klokan** [comment]
Thanks @tomchadwin
