### ISSUE TITLE
Reload Button in MVT menu to reload from source

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#146]
Currently "Refresh" button reloads from cache only (pbf's unpacked as GeoJSON files). 

Regarding this plugin I suggest that it clears the VT cache und reloads everything from source (by maintaining e.g. current view and connection settings).

BTW: This button IMHO should be used in general rarely and only when the user thinks, a (VT) layer is out of sync with the source.

**Comment by mnboos** [comment]
Done. The refresh button clears the cache before reloading.
