### ISSUE TITLE
Enhance error handling in "Add Layer..." dialog

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#147]
Given "Add Layer(s) from a Vector Tile Source" dialog in "Online" tab, after clicking on "Connect", currently a modal error dialog pops up saying "HTTP HEAD failed: status None". 

Proposal for "Add Layer..." dialog "Online" tab:
 * Instead (Window title) ”Loading Error” => “Error”
 * In case 'None' or HTTP error 404: => “Loading error. Resource not found. URL incorrect?”
 * In case 302: => “Loading error. Moved Temporarily. URL incorrect? Missing or incorrect API key?“
 * Catch all: „Loading error. URL incorrect?”

In tabs "MBTile" and "Directory" of "Add Layer..." dialog I currently don't see any errors. I am actually somehow confused when the display of layers list in dialog is updated?

**Comment by mnboos** [comment]
![image](https://user-images.githubusercontent.com/22575883/33242393-a5e5d324-d2d4-11e7-8c94-23b385236481.png)
