### ISSUE TITLE
Edit and New in Online connection not behaving correctly

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#148]
Given "Add Layer(s) from a Vector Tile Source" dialog in "Online" tab:
 * "New Connection" shows pre-set fields (same es "Edit"), but should show empty fields.
 * "Edit Connection": When changing just the "TileJSON URL" it works; bit when editing "Name" string, a new entry is being generated. Instead it should update the existing entry.

BTW: Rename "StyleJSON URL" to "GL Style JSON URL".

**Comment by mnboos** [comment]
This should already be fixed on the develop branch. Except for the rename of "StyleJSON URL" to "GL Style JSON URL"

**Comment by mnboos** [comment]
The style can be changed, but will be overwritten by an old value.

**Comment by mnboos** [comment]
Fixed
