### ISSUE TITLE
Predefined Vector Tile Sources (inc. some with API keys)

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#149]
In "Add Layer(s) from a Vector Tile Source" dialog, "Online" tab there's a list of predefined connections, as follows:
 1. "OpenMapTiles.com (default entry with credits)" 
 1. "Mapzen.com (default entry with credits)"
 1. "OpenMapTiles.com (with custom key)" 

For 1. OpenMapTiles and 2. Mapzen API, keys are provided by @klokan and @nvkelso and we're very thankful about that!

These two entries are disabled for "Edit" and "Delete", since we don't want users to remove nor re-use these keys too easily. "OpenMapTiles.com (default entry with credits)" in addition remains the default list entry, since it's the project - stemming from OSM2VectorTiles - of Geometa Lab HSR in cooperation with Klokan Technologies where everything began.

These are my considerations:
 * I'm open to any further default entries. 
 * I'd like to build-in as few "hidden code" as possible (e.g. hiding API keys) because of unnecessary technical dept.
 * I'd like to treat all providers equally (besides keeping OpenMapTiles.org the default list entry as explained above).
 * I'm happy to support other plugins to use MVT layers (like qgis2web from @tomchadwin)

**Comment by mnboos** [comment]
And what is the question?
