### ISSUE TITLE
Implement scale dependent zoom

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#15]
Scale dependent zoom cannot be enabled. The checkbox on the UI is disabled because the functionality is not yet implemented.

**Comment by mnboos** [comment]
This will not be implemented due to the decision, that it would infer to much with a proper user experience.

**Comment by sfkeller** [comment]
Reopening. Got several issues in new releases e.g. 
  1. Loading too IMHO many tiles (>32) at certain scales (to be optimized).
  1. Not loading Zoom 2 when given OMT and brand new QGIS project (no other layers loaded).
  1. Loading Zoom 3 instead Zoom 2 (="World) with "Zoom to Group" (right-click on Group in Layer Selector) given OMT source.
  1. Changing inadvertedly actual scale when loading a MVT reader connection given there are any other layers already loaded (to be reproduced and tested e.g. with a WMTS layer loaded via QuickMapTiles).
  1. Not loading anything when jumping directly to a scale 1:2'500 e.g. using OSM place search.

**Comment by sfkeller** [comment]
Here's a black box test (tbd. in unit tests?) of MVT Reader describing expected positive results which tests auto-load, zoom level/scale, styling/rendering, etc.:

 1. (Re-)Start QGIS.
 1. Load WMTS „OSM Standard“, e.g. using QuickMapServices. => World being displayed at 1:~200 mio. and zoom 2.
 1. Load MVT Connection „OpenMapTiles“ (with styling). => World being displayed at 1:~200 mio. and zoom 2. Zoom remains 2 unchanged.
 1. Also „Zoom to Group“ (right-click on group „OpenMapTiles“). => World being displayed at 1:~200 mio. and zoom 2. 
 1. Navigate to an extent at scale 1:2‘500 (zoom ~17, e.g. "Schlosshof Grüningen" or "Schloss Lenzburg") either with Mouse-Zoom-in or with search e.g. with Plugin „OSM place search“ => OMT buildings and streetnames are displayed.
 1. Remove legend entry „OpenMapTiles“ from Layers Panel, therefore deleting connection. => All MVT Connection related resources are removed and released (Zoom/Tile indicator is perhaps left over at lower right of QGIS window).
 1. Load MVT connection „OpenMapTiles“ again. => OMT buildings and streetnames are displayed. Scale 1:2‘500 (zoom ~17) remains unchanged.

**Comment by mnboos** [comment]
Works now, i.e. with the release 1.5.0, as you describe.
