### ISSUE TITLE
Layer filter not working

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#150]
![image](https://user-images.githubusercontent.com/22575883/33272244-dcf7f90e-d389-11e7-9ddb-00a8a7252275.png)

**Comment by mnboos** [comment]
Workaround: Don't select any layers in the table

**Comment by barryrowlingson** [comment]
What's happening is around line 565:

https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/master/ui/dialogs.py#L565

where this line:

`selected_layers = dict(map(lambda i: self.model.item(i.row()).text(), indexes))`

is trying to make a dict from a list of names, [u'poi', u'housenumber', u'place'] gotten from the text of the items. dict(that) fails.

**Comment by mnboos** [comment]
Instead of dict, it should probably be a list.

**Comment by mnboos** [comment]
Fixed
