### ISSUE TITLE
Tile request timeout?

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#152]
Perhaps I just hit a glitch, but I've just had QGIS hang while MBVTR is requesting tiles. What mechanisms are in place to prevent this happening?

For QGIS3, all tile requests could be sent to the new Task Manager to run in the background, but is there some failsafe for 2.x?

**Comment by mnboos** [comment]
In which QGIS version did this problem occur?

**Comment by tomchadwin** [comment]
Latest 2.18.

**Comment by sfkeller** [comment]
I think the only thing one can do as plugin, is to detect the downloading timeout and show an error to the user. 
BTW there's a (Re-)"Load features...." command in the plugin menu in Layers Toolbar which could be used to retry later. 
(I've looked at QMS and found this: https://github.com/nextgis/quickmapservices/blob/master/src/py_tiled_layer/tilelayer.py#L294 )

**Comment by tomchadwin** [comment]
I should clarify. The hang was not when initially loading the tiles from the MBVTR dialog. It happened while zooming MBVTs already loaded. I'll see if it reoccurs - everything slowed down quite badly earlier today.

**Comment by mnboos** [comment]
There was an issue that cancelling (due to reloading) may have lead to a memory leak because decoding wasn't actually cancelled.

**Comment by mnboos** [comment]
I fixed another issue in the networking part of the reader.

@tomchadwin If it happens again, please reopen this issue and, if possible, copy the log. Thanks a lot!

**Comment by sfkeller** [comment]
Just out of curiosity: What's happening when internet breaks before or during (re-)load of a remote source? What's the timeout in sec. and what's the error message the users gets?

**Comment by sfkeller** [comment]
Ok. Found it: timeout comes from QGIS and error messages are more user friendly as described in #147.
