### ISSUE TITLE
Initial tile load misses tiles

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#153]
When I connect to OpenMapTiles, I very rarely get all the tiles at zoom level 2. This is what I normally get:

![2017-11-29 09_31_08-qgis 2 18 14](https://user-images.githubusercontent.com/7840213/33367985-356b0fe0-d4e8-11e7-997d-09e7c8fc5259.png)

**Comment by sfkeller** [comment]
Yes; @mnboos is working on this.

**Comment by mnboos** [comment]
Fixed.
