### ISSUE TITLE
Labels too small - on Retina / HighDPI

### ISSUE THREAD

**Issue by klokan** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#154]
I am not sure - but it almost seems like the labels are too small in the default view:

![screen shot 2017-12-01 at 13 34 57](https://user-images.githubusercontent.com/59284/33483181-e6e4b374-d69c-11e7-9326-ffa3d9044fcd.png)

Is it related to my Retina display on Mac?

If yes, this would be a bug - which can be solved with QT HighDPI detection:
https://stackoverflow.com/questions/16527971/detect-hidpi-mode

**Comment by mnboos** [comment]
It's not a DPI issue, it's just the old, deprecated style. The style from the generator looks like this:

![image](https://user-images.githubusercontent.com/22575883/33524785-6a1cf8b4-d823-11e7-8f75-85928b20bd33.png)
