### ISSUE TITLE
Set source extents on layers

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#156]
The actual extents of the source should be set on each layer in order to allow the "Zoom to Group / Layer" functionality to work properly.

**Comment by mnboos** [comment]
@sfkeller Should I set the loaded extent, or the extent / bounds of the source?

**Comment by sfkeller** [comment]
Goal is to behave like other layers, so in OMT with base map defaults this is the world, and this is the same as e.g. WMS/WMTS "OSM Standard" (worldwide).
 * Given option "Auto Zoom" is checked (base map mode) the extent/bounds of the metadata (TileJSON, MBTiles, etc.) should be taken; 
 * else the loaded extent should be taken.

**Comment by mnboos** [comment]
Done. @sfkeller  Please test if it works as you expect.
