### ISSUE TITLE
Copyright decorator option

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#158]
Add a checkbox "Add Copyright to map" which extends and enables the QGIS map decorations option.

@sfkeller Not sure if I misunderstood you, but I shall implement this.

**Comment by klokan** [comment]
+1

Follow up on #145

**Comment by sfkeller** [comment]
Yes, but wait until I checked that this option is not perceived as intrusive from outside.

 * Check that the attribution text from metadata is taken.
 * If there is no attribution text from source; don't activate decorator.
 * Make sure you don't add the same attribution text twice.
 * Implement only &copy; and href (see also TileJSON spec.)

Enabled checkbox could be look like this: "[x] Add copyright to map".

BTW: Check lower case of other labels in the "Add..." dialog:
[x] Merge tiles
...
[x] Apply GL JSON style (if specified)
[x] Set project background color

**Comment by mnboos** [comment]
> BTW: Check lower case of other labels in the "Add..." dialog

Done

**Comment by sfkeller** [comment]
I double checked this issue and got to the conclusion that 
=> it is OK to add a checkbox "Add copyright to map". 

This checkbox is enabled by default, activates the copyright decorator in main canvas, following the rules mentioned above (don't add same attribution twice etc.)!

These are the sources:
 * Online: TileJSON spec. has attribution, optional (see above and spec.).
 * MBTiles: I think it has an optional attribution field too in table metadata.
 * Directory: t-rex currently produces no attribution/copyright entry in metadata.txt.

I also looked up how the Print Composer behaves in QGIS 2.14: 
 * There's a "Label" item, but no copyright decorator there.
 * Label has an "Item properties" tab/dialog with "Insert an expression..." and "Render as HTML"
 * If there exists a project variable e.g. @copyright, the expression for this label could be "&copy; QGIS, [% @copyright %]" (without parantheses).
* It would useful and symmetric, when the copyright decorator also would allow such expressions. I'll check and/or make an issue in QGIS.
* Actually I'm wondering if and how all this is implemented in QGIS 3. 

=> Look if it's possible to set project variable "@copyright" (not QGIS main settings variable). This must follow similar rules mentioned above (don't delete, don't add same attribution twice etc.)! See e.g. https://gis.stackexchange.com/questions/189075/how-to-change-a-project-variable-using-python . Omit this if it's too hacky.

**Comment by mnboos** [comment]
@tomchadwin Do you know how to access / modify the copyright decoration?

**Comment by sfkeller** [comment]
It's weird:
https://github.com/qgis/QGIS/search?utf8=%E2%9C%93&q=decoration&type=
shows the sip file (which should expose the C++ to Python API); but 
http://geoapis.sourcepole.com/pyqt/qstyleoptionviewitem#decorationSize-var
does not find any "QgsMapDecoration".
Perhaps @m-kuhn know's how.

**Comment by tomchadwin** [comment]
For QGIS3, is it https://qgis.org/api/classQgsProject.html#a7488b66a620c80d2891e686d8229770d?

**Comment by tomchadwin** [comment]
For QGIS2, it might be something you get at via `QgsProject.readEntry()`. That's certainly how you 
access the scale bar settings - there is no specific API. Search the qgis2web codebase for 'scalebar', and also have a look at the contents of a .qgs file. But I don't know for sure.

**Comment by mnboos** [comment]
@sfkeller @klokan There is no QGIS api for that in QGIS 2. This issue can only be solved for QGIS 3.
