### ISSUE TITLE
Handling more than one MVT source?

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#161]
Currently a new MVT source can be added but the plugin leaves all current sources "unmanaged". The plugin IMHO should...
 1. Either inform user, remove the previous source and load the new one.
 1. Or support more than one MVT sources.

**Comment by mnboos** [comment]
Notify user, that this is a restriction of the current plugin implementation. Only the latest source is connected and will be updated. "You may save or delete this layer group".

**Comment by mnboos** [comment]
Done.

![image](https://user-images.githubusercontent.com/22575883/34322789-df1dcaa8-e831-11e7-8596-2933105bc3ca.png)
