### ISSUE TITLE
Plugin crashes QGIS on OS X

### ISSUE THREAD

**Issue by kbevers** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#163]
Upon installing the plugin via the plugin manager, QGIS segfaults with the following message:

```
$ qgis2
...
src/core/qgspythonrunner.cpp: 32: (run) [2284ms] Running pyplugin_installer.instance().installPlugin('vector_tiles_reader')
src/core/qgsnetworkaccessmanager.cpp: 189: (createRequest) [1ms] Adding trusted CA certs to request
src/core/qgsnetworkaccessmanager.cpp: 94: (queryProxy) [0ms] using fallback proxy for https://plugins.qgis.org/plugins/vector_tiles_reader/version/1.5.0/download/
2017-12-04 19:44:41.955 QGIS[66589:15314555] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
/usr/local/bin/qgis2: line 12: 66589 Segmentation fault: 11  /usr/local/opt/qgis2/QGIS.app/Contents/MacOS/QGIS "$@"
```

This is on the latest OS X, QGIS 2.18.14 installed with Homebrew (everything is up to date). This happens both for v. 1.4.1 and 1.5.0 of the plugin. I realise that the above error message is not much to work from. I'm happy to provide any other debug info that might help find the cause of this problem.

**Comment by mnboos** [comment]
Thanks for reporting the problem. Do you have a proxy configured in QGIS?

**Comment by sfkeller** [comment]
Yes same question from me:
  1. Did you enable "use proxy for web access"; and if yes, is this proxy working elsewhere?
  1. Did you add CA certs and if yes is it valid (i.e. working elsewhere)?

**Comment by kbevers** [comment]
No proxy and no certificates.

**Comment by kbevers** [comment]
Any other ideas on how I can debug this?

**Comment by mnboos** [comment]
Am I right, that this error happens _before_ the plugin gets actually installed?

**Comment by kbevers** [comment]
Well... It's more like during install. It's hard for me to tell exactly when it fails, but it definitely happens after pressing "Install plugin". If I manually copy the plugin into the `.qgis2` folder QGIS crashes when starting up. Presumably when trying to load the plugin.

Could it be some dependency required by the binaries that I haven't got on my system?

**Comment by mnboos** [comment]
It's not the plugins binaries. They are only loaded at runtime and if they cannot be loaded, nothing happens.

Currently, I'm clueless, maybe @sfkeller has another idea.

**Comment by sfkeller** [comment]
I'll check with a little MacBook Pro until coming monday.

**Comment by mnboos** [comment]
@sfkeller Any updates from your side?

**Comment by sfkeller** [comment]
Plugin v1.6.0 worked on macOS 10.13.2 using a fresh installation of QGIS 2.18.14 from kyngchaos.
So; could not replicate the problem descibed above.

**Comment by kbevers** [comment]
It must be a problem on my end then. I don't know what else I can do to determine where the problem lies. I think this should be closed.

**Comment by mnboos** [comment]
Can you install other plugins?

**Comment by kbevers** [comment]
Yes.

**Comment by jaakla** [comment]
Did you get it sorted out? I just have the same issue - qgis crashed during install, and now it does not start at all - just silently crashes with latest message "loading plugins" in splash screen.

macos 10.12.6 qgis 2.18.13

**Comment by kbevers** [comment]
Nope.

If you delete the plugin folder from `./qgis2/python/plugins/` you can start QGIS again.

**Comment by jaakla** [comment]
Updated qgis to currently latest 2.18.14 , still same. Attaching full crash report, it seems to have references to specific lines of code: [QGIS_2017-12-22-111049_Jaaks-MacBook-Pro-2.crash.zip](https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/files/1582033/QGIS_2017-12-22-111049_Jaaks-MacBook-Pro-2.crash.zip)

**Comment by sfkeller** [comment]
Thanks. This crash report could give a clue about the issue.

> If you delete the plugin folder from ./qgis2/python/plugins/ you can start QGIS again.

I actually would not delete the whole folder but only subfolders (= plugins) within ./qgis2/python/plugins/ .

**Comment by kbevers** [comment]
> I actually would not delete the whole folder but only subfolders (= plugins) within ./qgis2/python/plugins/ .

That was what "the plugin folder" refered to, although I can see why that is not very obvious.

**Comment by mnboos** [comment]
Is this still an issue?

**Comment by kbevers** [comment]
I don't know, to be honest. I've moved to QGIS3 and haven't had a reason to use vector tiles since this issue was first reported. If no one else can confirm this issue I think it should be closed.
