### ISSUE TITLE
Enable OTF EPSG:3857 on tiled layer add

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#165]
Following workflow:
 1. Given a new QGIS project. Switch on Project Property "Enable on-the-fly tranformations (OTF)".
 1. Load e.g. any GeoJSON file (see attachment). GeoJSON officially is CRS 4326, so Project CRS is set to "EPSG:4326" too.
 1. Load an MVT, e.g. "OpenMaptiles.org" Online Connection, which is EPSG:3857.
 1. QGIS project now changes to "EPSG:4326 (OTF)" - which is wrong and displays nothing really. 

But MVT reader should enable OTF and switch to 3857 - or to what is indicated in the metadata of the source if there exists a field "CRS" (not-yet standardized; see https://github.com/mapbox/tilejson-spec/issues/24 ; I hope @flippmoke follows what we are struggling here ;-) ).

Ideally MVT reader could transform all tiles to project CRS on-the-fly if required (raster tiles can)! In fact, looking at Settings of QuickMapTiles, it asks the user "Enable OTF EPSG:3857 on tiled layer add". 

[2points.txt](https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/files/1540683/2points.txt)

**Comment by flippmoke** [comment]
There is no real difference between data converted directly from the two
projections to a vector tile's projection.

ESPG:4326 -> (A projection of a VT)
ESPG:3857 -> (A projection of a VT)

The only thing of worth to note is the bounds of a tileset (which is often
based upon the bounds of ESPG:3857 area). If you can calculate the bounds
of any tile, you can easily reproject the data in the tile if you know the
"extent" of its layer.

Data in a tile isn't stored in any real projection, as each tile is in a
coordinate system based on that tile (and its location in the tileset).

**Comment by sfkeller** [comment]
Thanks for clarifying. This in fact makes it realistic that MVT reader can support different project CRS.

There are still following issues remaining:
 1. Current MVT reader does not display tiles in canvas given above test where project CRS says "EPSG:4326 (OTF)" (which is a bug).
 1. Current MVT reader follows an extension from @klokan to horse-shoe data of CRS other than 3857 into the CRS agnostic Mapbox tools like Leaflet (which is a hack, though I don't know alternatives currently). 
 1. Even if it's EPSG:3857 by default, a metadata (like TileJSON spec.) should IMHO endorse a "CRS" attribute (as proposed in https://github.com/mapbox/tilejson-spec/issues/24 ).

**Comment by mnboos** [comment]
> 1. Current MVT reader does not display tiles in canvas given above test where project CRS says "EPSG:4326 (OTF)" (which is a bug).
> 2. Current MVT reader follows an extension from @klokan to horse-shoe data of CRS other than 3857 into the CRS agnostic Mapbox tools like Leaflet (which is a hack, though I don't know alternatives currently).

1. is exactly the expected result of 2.  --> Either 1. is working, or 2. They're mutually exclusive.

With the workaround mentioned in point **2.** disabled, it works like a charm:

![image](https://user-images.githubusercontent.com/22575883/33765072-89d899cc-dc17-11e7-8831-b037835ba375.png)

**Comment by mnboos** [comment]
Commit 562b6d60cacf1bf5abe0db1411a9bcba2f4dc112: Checkbox added to enable/disable ignoring the CRS from the metadata.
