### ISSUE TITLE
Analysis Defaults not showing tiles in current map canvas (but at corrected area)

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#166]
Following:
 * Using QuickMapServives, load 'OSM Standard'.
 * Goto to any neighborhood with zoom level 16 (like Dättwil).
 * Load MVT source with "Analysis Defaults".
=> Nothing is displayed in current main map canvas.

The MVT plugin seems to load vector tiles at different area and zoom level, e.g. in Italia at zoom level 5.

**Comment by mnboos** [comment]
I cannot reproduce the behaviour you describe. Could you please make a screenshot of the connections dialog **before** you click on "Add"? Additionally, a copy of the log from the log panel would be very helpful.

**Comment by mnboos** [comment]
Has been solved; you still had zoom-level 5 set. The ui behaviour has been improved.
