### ISSUE TITLE
Loading mvt sources URL in QGIS

### ISSUE THREAD

**Issue by raosaeedali** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#169]
Hi,
I want to load mvt tiles into QGIS through a URL service `https://abc.com:8080/buildings/{z}/{x}/{y}.mvt` But, the menu in the plugin allows TileJSON URL. Is there any way I can load mvt directly to QGIS?

**Comment by mnboos** [comment]
Hi

Unfortunately, this is not possible. The plugins requires some metadata, like min- and maxzoomlevel. Due to this, it doesn't work like this. If the files are located on your harddisk, you could maybe use the directory connection. However, even this option requires metadata.

**Comment by mnboos** [comment]
Have a look at this: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/wiki/Help#directory

There is also described, which metadata is required exactly.

**Comment by raosaeedali** [comment]
@mnboos Thanks for your timely response.

**Comment by raosaeedali** [comment]
Sorry to bother you again but is there any tool that can help me in devising a meta-data file from mvt files or make my own meta-data?

**Comment by mnboos** [comment]
I suggest you download a valid MBTiles (for examples from www.openmaptiles.org) and inspect its metadata by opening the file in a sqlite viewer.
