### ISSUE TITLE
Progress bar dialog constantly takes focus from all other applications

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#17]
Experienced on Win7x64

**Comment by mnboos** [comment]
I think that's due to a "feature" of the progress dialog to show itself, if it isn't visible. Didn't realize it would take the focus from other applications and therefore I fixed it in 606efdf.

**Comment by tomchadwin** [comment]
Fix confirmed - thanks again,
