### ISSUE TITLE
Implement Support of Vector Tiles Reader for QGIS 3

### ISSUE THREAD

**Issue by xkomczax** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#172]
Plugin states:

> This plugin is incompatible with this version of QGIS
> Plugin designed for QGIS 2.18 - 2.99

, even thought I am running QIGS 2.99 (on Windows 7).

![plugin-manager](https://user-images.githubusercontent.com/3698242/34992314-0da11ac6-facd-11e7-85a1-4187c395e121.png)
![qgis-version](https://user-images.githubusercontent.com/3698242/34992315-0dc38d04-facd-11e7-82f6-77d27aff0747.png)

**Comment by sfkeller** [comment]
First I would adapt metadata.txt "qgisMaximumVersion=2.99" to a version tested.
I labelled it a bug also because 2.99 really is a weird way to speak of a Version 3 :-).
In fact, I labelled it also as an "enhancement" since the main goal of this plugin is/was QGIS 2.18.8/2.14.15 LTR, not Version3.

**Comment by tomchadwin** [comment]
See https://lists.osgeo.org/pipermail/qgis-developer/2017-December/051023.html

**Comment by mnboos** [comment]
I will adapt the metadata to a tested version, as the current QGIS 3 "compatibility" is more an experimental state. As long as QGIS 3 has not been officially released, I won't invest much time there.

**Comment by tomchadwin** [comment]
QGIS is now in feature freeze for v3, which is to be launched towards the end of February. I can't remember the precise date, but one has been published (possibly 23 Feb?). While the API is *not* officially frozen, I still think it is stable enough to work on full v3 compatibility now, handling any further API changes as they appear in the nightlies.

**Comment by mnboos** [comment]
Okay nice to know, thanks.

**Comment by xkomczax** [comment]
[QGIS 3.0 has been officially released](http://blog.qgis.org/2018/02/23/qgis-3-0-girona-is-released/)

**Comment by mnboos** [comment]
Thanks for the info @xkomczax . That means I should ASAP assure the QGIS 3 compatibility.

**Comment by astrojuanlu** [comment]
Looking forward to it :)

**Comment by sfkeller** [comment]
Can I close this issue?

**Comment by mnboos** [comment]
From my side: yes
