### ISSUE TITLE
Check for compatibility of MBTiles Spec 1.3

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#174]
See https://github.com/mapbox/mbtiles-spec/pull/47

**Comment by mnboos** [comment]
**vector_layers** is present, which is an important thing for the reader.

**bounds**, **minzoom** and **maxzoom** are optional in the metadata table. I can live with that, even though I don't see why it's not a MUST for the metadata table. Now clients have to lookup in the data to extract the required metadata by themself.

**Comment by sfkeller** [comment]
1.3 released! https://github.com/mapbox/mbtiles-spec 
Now waiting for an update of TileJSON spec. https://github.com/mapbox/tilejson-spec/issues/14
