### ISSUE TITLE
Can I identify these layers via the Python API

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#18]
Is there any way in PyQGIS to identify that the imported layer/group is a vector tile one?

Background: I code qgis2web, and it would be great to be able to export such vector tile layers back out to webmaps. To do that, I'd need to be able to find out which items in the layerTree are imported vector tile layers, and what the source is.

**Comment by mnboos** [comment]
There are already some custom attributes on feature level (_zoomLevel, _featureNr, _col, _row). However, these might still change. I think it might be a good idea, to add metadata to the layer to identify it as vector tile layer.

@sfkeller what name would you suggest for such an attribute? How about "_vectorTileSource" that contains  the filename with or without the path of the mbtiles. For server connections it would show the url to the pbf.

**Comment by sfkeller** [comment]
@mnboos You want to attach to every feature the mbtiles filename? Is this really needed? I think something like _vectorTileSource belongs on a single place at layer properties - in fact, there must be a PyQT variable already existing.

**Comment by mnboos** [comment]
@sfkeller no not on every feature, only on every layer.

**Comment by sfkeller** [comment]
Layler level variables? http://nyalldawson.net/2015/12/exploring-variables-in-qgis-pt-3-layer-level-variables/

**Comment by tomchadwin** [comment]
Or layer custom properties? 

https://qgis.org/api/classQgsMapLayer.html#a7bf94cfa08abc37b75cc53dc921bb15e

**Comment by mnboos** [comment]
This is not yet solved. I propose a layer level variable that has the value of the layer-source (i.e. the path to the mbtiles or the xyz-url)

**Comment by mnboos** [comment]
Done. You can find a layer variable "vector_tile_source" with the name of the corresponding source. If you wish any extensions or changes, please let me know.

**Comment by tomchadwin** [comment]
Sorry to be slow, but how do I retrieve that value in PyQGIS?

**Comment by mnboos** [comment]
I use 
`QgsExpressionContextUtils.setLayerVariable()`
to set the variable. But it seems there's a problem, as on some layers the value isn't set. Ugh.. have to investigate that...

To answer your question:
```python
scope = QgsExpressionContextUtils.layerScope(my_layer)
if scope.hasVariable('vector_tile_source'):
   src = scope.variable('vector_tile_source')
```

**Comment by tomchadwin** [comment]
Thanks. Are you sure `QgsMapLayer.customProperty()` would not be an easier approach?

**Comment by mnboos** [comment]
Correct me if I'm wrong, but the custom properties are not visible anywhere in QGIS? Personally, I'd prefer something "visible", but yes, I can use custom properties instead as the layer level variables don't seem to be reliable.

I added a custom property with the same name 'vector_tile_source'. Let me know if it works.

**Comment by tomchadwin** [comment]
No, I don't think they are visible in the GUI.

**Comment by tomchadwin** [comment]
Confirmed custom property works, but it seems to return the filename only, no path, no file extension. Both of those would be useful, if they can be added. Thanks for the work!

**Comment by mnboos** [comment]
That's right but I can also include the filename and path.

**Comment by mnboos** [comment]
It's now filename/url

**Comment by tomchadwin** [comment]
OK, I've got a very rough implementation up and running for Leaflet exports. It examines the layers, and if that customProperty is present, it exports it as a `L.VectorGrid` layer. However, I am not sure this approach is going to work:

- it creates separate Leaflet layers for each layer, but I think the tile data contains info for all layers
- it styles the layer, but all other data within the tile for that is unstyled, which in Leaflet means it is visible

I think the best way to approach this is to make the top-level layer group identifiable in some way - can layer groups have customProperties? A single L.VectorGrid layer could then be exported, combining all the styling rules for the different QGIS layers.

As you can tell, I'm still feeling my way with this, and am not sure I am understanding the mechanics of it all well enough to work with it properly. I'll keep at it, though.

**Comment by tomchadwin** [comment]
No, scratch that, I think I'll use the per-layer customProperty you have set up, and build up a single style var for all layers which have the same value for that customProperty. I'll report back...
