### ISSUE TITLE
Can MVT vector tiles be added from a local server?

### ISSUE THREAD

**Issue by Nate-Wessel** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#181]
This is probably already possible, but perhaps not yet documented. I'm trying to use this plugin to view vector tiles tiles generated by [OSRM](https://github.com/Project-OSRM/osrm-backend) and provided as a service, as documented [here](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#tile-service). In my case, I can access these tiles at `http://localhost:5004/tile/v1/transit/tile({x},{y},{z}).mvt`, and I can see the tiles as expected with Mapbox GL, which confirms that the server is running properly. 

It seems like perhaps I need to create a json configuration file to direct the plugin to the right source?

**Comment by sfkeller** [comment]
Yes, that's possible and just a metadata.json file away :-(.  This issue is related to #112 and #170.

This plugin (and other db related SW) need this metadata and there's little hope now when reading the gentle attempts where Mapbox finally updates their mbtiles spec. (hopefully soon also TileJSON): https://github.com/mapbox/mbtiles-spec/pull/47/#issuecomment-362702815 .

I know that it's suboptimal that this metadata file is not yet generated by all vector tile generators.  My idea is to write a standalone Python program based on OGR which generates this metadata.

**Comment by Nate-Wessel** [comment]
Thanks for the quick reply! So if I understand correctly, it's as easy as making a configuration file, but there is no standard format for that file yet? I tried making one anyway, 

````
{
	"tilejson": "2",
	"name": "OSRM debug tiles",
	"tiles": [
		"http://localhost:5004/tile/v1/transit/tile({x},{y},{z}).mvt"
	],
	"vector_layers": [
		{
			"id": "speeds", 
			"description: "", 
			"fields": {
				"speed":"Integer", 
				"is_small":"Boolean",
				"datasource":"String",
				"duration":"Float",
				"weight":"Integer",
				"name":"String",
				"rate":"Float"
			}
		}
	],
	"minzoom": 12,
	"maxzoom": 20,
	"center": [ -81.6606, 30.34, 15 ]
}
````

but I get the following error  `The field 'vector_layers' is required but not found. This is invalid TileJSON.`, which seems silly since `vector_layers` is specified, if incorrectly.

**Comment by sfkeller** [comment]
I think you're very close :-). I'm sure @mnboos can help you. I'm also (almost) sure there must be a metadata.json template in the docs - at least I asked him to publish one.

**Comment by mnboos** [comment]
@Nate-Wessel I admit, it's a bit hidden: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/wiki/Help#metadatajson

I'm wondering right now, why your metadata.json is declined. On the first sight, it looks pretty good.

**Comment by Nate-Wessel** [comment]
I tried it again with a few different fields and I'm not sure I see what's going wrong here either. I seem to have all the required fields, though I'm not giving a `json` field with an escaped vector_layer attribute as in the example. 

There is one complication that I didn't mention. If I give a filepath to the metadata.json file (e.g. `/home/nate/metadata.json`), stored locally on my computer, in "add vector tile layer" -> "server" -> "edit connection" -> "TileJSON URL", I get the error 
```
Loading error: Protocol "" is unknown 

URL incorrect?
```
To get around this, I hosted the file on a personal website so I could get it with HTTP... but I wonder if the different domains (website referring to a service on localhost) could be part of the problem?

In case it makes a difference, I should also mention that I'm not supplying a style URL, as I'd prefer to use QGIS to do the styling.

**Comment by mnboos** [comment]
```
Loading error: Protocol "" is unknown 

URL incorrect?
```

That's a result of the path not starting with *http(s)*. Actually, it would make sense to support locally stored tilejson files but at the moment, that's not implemented. As a result of this, the current scenario won't be working, sorry for the confusion.

**Comment by mnboos** [comment]
See #186
