### ISSUE TITLE
Add Mapcat vector tile support 

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#182]
Add Mapcat vector tiles as free (sponsored) service - if possible together with a new MB GL JS style - to become another "Server Connection" in this QGIS plugin (similar to #78 (Mapzen/Nexten).

**Comment by mnboos** [comment]
Done

**Comment by sfkeller** [comment]
Martin: We have to withdraw MAPCAT vector tiles in the reader as one of the predefined "Server Connection". Recently they wrote me "Unfortunately until the business circumstances is not changed the global MAPCAT service will be suspended.".

**Comment by mnboos** [comment]
Okay will do.

**Comment by mnboos** [comment]
Done (0c4167dbbfad10ada295ab89ed33d4bd9c18b9ab)
