### ISSUE TITLE
Problem uninstalling the plugin (Win 7 Enterprise, QGIS 2.18.14)

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#183]
Given QGIS 2.18.14 and a good'ol' Win 7 Enterprise, I'm having following problem uninstalling plugin 1.7.2:

1. Start QGIS
1. Open a QGIS project which contains just one source, a Server Connection (default OpenMapTiles)
1. Close the QGIS project
1. When Uninstalling => A red error message in QGIS window says some files are locked in plugin directory ("<<sys_user_dir>>\.qgis2\python\plugins\vector_tiles_reader") .
1. Then quit and restart QGIS,
1. Open Plugin Manager => Manager says plugin is invalid (e.g. metadata missing).

After deleting the plugin directory manually I could reinstall the plugin successfully. _(So after all, this is not a critical bug, since who ever wants to uninstall this great software anyway :-))_ 

I assume some files are not closed by the plugin - or worse: some helper files need to be left open? Nasty thing is, that the error comes after the deinstallation command already deleted some files already, like e.g. metadata.txt. This could be something to enhance.

**Comment by tomchadwin** [comment]
Is this connected to earlier discussions about whether MBVT connections remain open after the layers are removed?

**Comment by mnboos** [comment]
@sfkeller Did this happen again?
