### ISSUE TITLE
customProperty("VectorTilesReader/vector_tile_source") now friendly name, not URL?

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#184]
That's what I seem to see. Or have I got something wrong?

**Comment by tomchadwin** [comment]
Change was here:

https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/commit/48875b6a7707c3500c44568de35b4ca5bc93430d#diff-d51629ab2ff8c0f5ea17b1debd295744L665

If you cannot revert this change, can I suggest another `customProperty`, such as "vector_tile_url". The qgis2web vector tile export is broken by this change.

**Comment by mnboos** [comment]
That's correct, I needed the name of the connection instead of the url (which btw. can be the same for different connections).
If you need the url, I  can merge the PR.

**Comment by tomchadwin** [comment]
Yes, I need the URL, so a merge would be great.

**Comment by tomchadwin** [comment]
Thanks!
