### ISSUE TITLE
Progress dialog needs cancel button

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#19]
These are often going to be long, IO-intensive operations, so the ability to cancel is important.

**Comment by mnboos** [comment]
This is already planned and will be implemented soon.

**Comment by tomchadwin** [comment]
Splendid. Thanks!

**Comment by mnboos** [comment]
Done with release v0.5.0-beta

**Comment by tomchadwin** [comment]
Thanks - confirmed that it kind of works, but I'll open a new issue for the problem.
