### ISSUE TITLE
Is there any tools for convert qgis style into mapbox-gl-style?

### ISSUE THREAD

**Issue by fanvanzh** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#197]
Is there any tools for convert qgis style into mapbox-gl-style?

thank you !

**Comment by mnboos** [comment]
No, not that I know. Maybe @tomchadwin can help.

**Comment by tomchadwin** [comment]
I don't know of any. I thought about adding a Mapbox GL export option to qgis2web, but have never done so.

**Comment by fanvanzh** [comment]
thank you for your answer. I decide to develop one plugin.
