### ISSUE TITLE
pathing error, but what does it mean?

### ISSUE THREAD

**Issue by bblobbett** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#199]
upon trying to load a MBTile file I get this error

An error has occurred while executing Python code: 

TypeError: stat: path should be string, bytes, os.PathLike or integer, not tuple 
Traceback (most recent call last):
  File "C:/Users/svanroy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\ui\dialogs.py", line 226, in _select_file_path
    if open_file_name and os.path.isfile(open_file_name):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not tuple

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.1-Girona Girona, a86bec25eb 

Python Path:
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/svanroy/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/svanroy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:/Users/svanroy/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\svanroy\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs

**Comment by mnboos** [comment]
Thank you for the report. 

I fixed the bug with commmit d860b7842cdeefea9bfdafbe2e5762d603fdaaca which will be included in the next release.
