### ISSUE TITLE
Unable to open local .mbtiles file

### ISSUE THREAD

**Issue by doskabouter** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#201]
On windows 7, Qgis 3.0.1
When I open a .mbtiles file, I get an error that some function parameter must be a string instead of a tuple.

This seems to be caused by the QFileDialog.getOpenFileName returning a tuple (selectedfilename,"Mapbox Tiles (*.mbtiles)") in dialogs.py, line 225.

For now, I set open_file_name to open_file_name[0] and that seems to solve the issue.

**Comment by tomchadwin** [comment]
Already fixed in master, I think, by https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/pull/200/commits/d860b7842cdeefea9bfdafbe2e5762d603fdaaca

**Comment by mnboos** [comment]
Correct, thanks @tomchadwin 

Due to the unavailability of the QGIS plugin store, I was unable to release the latest version 2.0.1 until now. At this moment, the new version should already be available for download.
