### ISSUE TITLE
Enabling Vector Tiles Reader causes crash on Fedora 28

### ISSUE THREAD

**Issue by dylrich** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#203]
Hi all,

I can successfully install the plugin, and have confirmed the files are in the correct place in my plugins directory. However, upon enabling the plugin, QGIS will think for a few seconds and then crash consistently, every time. I am using QGIS 3.2 on Fedora 28. I don't believe this behavior was happening in early 3.0 releases, but I could be mistaken. If there is other information that I am not providing that could be useful for debugging, I am happy to track it down. Would love to be able to use this plugin again!

Thanks for your time, and I appreciate the hard work put into this.

**Comment by sfkeller** [comment]
Hi Dylan. This plugin was definitely not yet tested with 3.2. So we appreciate your testing activities and debugging info.

**Comment by mnboos** [comment]
Thanks @dylrich and sorry for the delay. I tested the plugin with 3.2 and there were indeed some errors, at least with the predefined connections (HTTP status 301 has not been handled correctly). However, this may only be valid for windows, I'll test it on Ubuntu too but I don't have a Fedora at hand.

Would you mind having a look at the temp folder of your system if there's a folder "vector_tiles_reader" with a log.txt file?

**Comment by kuon** [comment]
I have the same issue using archlinux.

launching qgis from the command line produces the following output:

```
QGIS died on signal 11ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 0
``` 

I found the log file, but it was empty.

**Comment by dylrich** [comment]
Hi there - sorry for the late reply. There is a log file on my system, but like @kuon, mine is empty.

**Comment by mnboos** [comment]
I know it's been a while since, but the logging has been fixed. It now works in QGIS 3 as well as on the filesystem.

**Comment by mnboos** [comment]
And because I can't reproduce this, I will close the issue. Feel free to open it again if necessary.
