### ISSUE TITLE
Layer Z order

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#205]
I'm testing OS ZoomStack mbtiles locally (https://www.ordnancesurvey.co.uk/blog/2018/07/join-os-open-zoomstack-trial/?utm_source=Twitter&utm_medium=social&utm_campaign=SocialSignIn&utm_content=Zoomstack). On opening it, layer groups are put in alphabetic order. Is there no concept of layer order/z-index in MBTiles? If not, please close the issue. If there is, can it be read and implemented in the QGIS layer tree?

cc @charleyglynn

**Comment by mnboos** [comment]
As far as I know, the layer order is not  specified in any MBTiles file. Even though I think it would make sense. However, I don't think that will happen any time soon in the MBTiles specification.

**Comment by tomchadwin** [comment]
I came to the same conclusion after opening this issue. Thanks.

**Comment by sfkeller** [comment]
The layer order is and should not be part of any data source (like with any data schema). Ordering is rather a property of a query and specifically of a style. In fact, the same layer, like feature class water, is often being used twice, once for the polygon rendering (which happens to be below lines, nodes and text) and once for the text labels (which are on top).

**Comment by sfkeller** [comment]
Having said this, there's some concept of z-value in order to layer ways of same type. In OSM this is called "layer": https://wiki.openstreetmap.org/wiki/Key:bridge#Layers . This is e.g. used als filter in styles.

**Comment by tomchadwin** [comment]
OK, and I can't currently get the style converter to work (#207), so that probably would have done it for me. Thanks.
