### ISSUE TITLE
Reopened project - no new features load when pan/zoom

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#208]
- new project
- add local MBTiles
- save project
- close project
- reopen project

Some layers now claim no have no geometry.

**Comment by tomchadwin** [comment]
Having tested this more, is it that layers not present in the current view show up as tables without geometry? And do they change to layers with geometry when they come into the view?

**Comment by mnboos** [comment]
What do you mean by "tables without geometry"?

It is correct, that the actually available data is only loaded for the visible extent. This is done for better loading performance.

**Comment by tomchadwin** [comment]
Sorry for delay (was on holiday). I mean this (in the layer tree):

![2018-07-30 12_16_46-zoomstack_api - qgis](https://user-images.githubusercontent.com/7840213/43394427-a1f7c562-93f2-11e8-919b-ba90fb38e0fb.png)

**Comment by tomchadwin** [comment]
OK, can someone check this for me: I'm concerned that if you reopen a saved project, layers which had no features loaded/rendered at the time of saving remain NoGeometry even if you pan/zoom to where the geometry should once again be loaded/rendered. I hope that sentence makes some kind of sense. If I'm right, this could be quite a major issue.

**Comment by mnboos** [comment]
@tomchadwin The picture you posted above, did you check if the geosjon file exists or not?

**Comment by tomchadwin** [comment]
I didn't, I'm afraid. Away for a couple of weeks, so will have to check when I get back. Wondering if in fact this is another manifestation of #210? If so, this behaviour wouldn't occur if the layers are left in their original folder structure. I'll have to check.

**Comment by tomchadwin** [comment]
The geojson file does exist.

**Comment by mnboos** [comment]
Could you please copy the content of the file?

**Comment by tomchadwin** [comment]
Of course now, I do not get the `NoGeometry` text. Will post content of file if I can recreate again.

**Comment by tomchadwin** [comment]
I cannot now recreate. I'll close, and reopen if it happens again.

**Comment by tomchadwin** [comment]
Reopening - I've had this occur again, but with a `Server` source.

**Comment by tomchadwin** [comment]
Steps to recreate:

1. Connect VTR to server, add layers to project
2. Save project and close QGIS
3. Reopen QGIS and project

In my test case, only one layer loads, the rest show up as table icons in the layer tree. The contents of one of their temp GeoJSON files is:

```json
{
    "tiles": [],
    "source": "os-zoom",
    "scheme": "xyz",
    "layer": 0,
    "zoom_level": "contours",
    "type": "FeatureCollection",
    "crs": {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:EPSG::3857"
        }
    },
    "features": []
}
```

**Comment by tomchadwin** [comment]
Actually, no need to close QGIS. Simply reopen the project, and I get this behaviour.

**Comment by tomchadwin** [comment]
Confirmed with OpenMapTiles, Nextzen, and Ordnance Survey Zoomstack.

**Comment by tomchadwin** [comment]
Let me know if there's anything I can do to help debug/test.

**Comment by mnboos** [comment]
Made a quick test and couldn't reproduce, will try it later.

**Comment by tomchadwin** [comment]
Tried reinstalling the plugin, but my connections were still there. I want to make a clean start - where are the connection details stored?

**Comment by mnboos** [comment]
Deleting them via connections dialog is the fastest way I guess.

**Comment by tomchadwin** [comment]
Sure, but how do I get the out-of-the-box default connections, in that case? Will reinstalling the plugin recreate them?

**Comment by mnboos** [comment]
No, it will not. There is no way to achieve that automatically.

**Comment by tomchadwin** [comment]
OK, thanks. Am starting as clean as I can, and trying to recreate.

**Comment by tomchadwin** [comment]
I now cannot recreate, which makes me think it must have been bad config of some kind. I'll close for now - apologies for the noise - and reopen if I get a recurrence.

**Comment by mnboos** [comment]
No worries, just reopen if there are problems.
