### ISSUE TITLE
AttributeError: 'ConnectionsDialog' object has no attribute 'connect' 

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#209]
Occurs when the Refresh button on the MBTiles tab is pressed

**Comment by mnboos** [comment]
Thanks, I'll fix that.

**Comment by mnboos** [comment]
It took a long time, but finally, it's fixed (06d961382c21176ba00be142b9c585b2047475aa) and will be released soon.
