### ISSUE TITLE
Rendering Fonts

### ISSUE THREAD

**Issue by nevi-me** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#211]
I'm using QGIS 3.2.1 with this plugin, street names and city names don't display on QGIS. Instead of city names, there's "?" question marks on the map.

I have both QGIS 3 and 2 installed, but I can't open 2. Does anyone know if the plugin works well with 2, or is this a limitation?

**Comment by mnboos** [comment]
It should work better with 2 than with 3.

**Comment by sfkeller** [comment]
Can you provide a log or other information which could indicate why the font is not rendering in QGIS 3.2.1 in your installation(s)?

**Comment by nevi-me** [comment]
What kind of information would be good? I can provide a screenshot of 3.2 and 2.*, where fonts are being rendered in 2.*

Where can I find a QGIS log?

**Comment by sfkeller** [comment]
Open "Log Messages Panel" in QGIS in te very down right corner.

**Comment by tomchadwin** [comment]
> Where can I find a QGIS log?

`View > Panels > Log Messages` - there is a Vector Tiles Reader tab, though if there is no useful information there, you could look at some of the other tabs.

Also, it would help if someone else could recreate this issue. Are you using a public vector tile server to which one of us could connect?

**Comment by nevi-me** [comment]
@tomchadwin I don't have a Vector Tiles Reader tab on my logs, as per below

![snip1](https://user-images.githubusercontent.com/1876878/44992712-5b82f900-af98-11e8-8429-593a7bbac374.png)

I used the Mapcat.com (with default credits) server, and that rendered those question marks. The `INFO   :` log there on the tab is the only thing that seems to get generated in response to me dragging the map around.

I also cleared the caches with `Vector > Vector Tiles > Clear Cache` to check if that results in more log messages being generated.

I'm running a local vector tile server, but it's based off the klokantech Docker repo. Since I can reproduce the problem with MapCat, I don't think it's anything wrong with my tile server.

I'm using Windows 10, and Vector Tiles Reader is the only plugin that I've installed. As mentioned before, QGIS 2.18.22 seems to be working with no issues.

**Comment by mnboos** [comment]
Normally, the question marks appear if something in a style has not been implemented, like highway shields for example. I'll have a look into as soon as possible.

**Comment by nevi-me** [comment]
Is there anything that I could do to get more debug info, or help with getting more details about the issue?

I've tried a few different map servers, and all of them return `?` instead of text on QGIS 3

**Comment by sfkeller** [comment]
Thanks for your offer. This "?" issue is well known and relates to the fact that a style may refer to a font  (or symbol) which is not installed at the client. 

We're little bit short of support here as this is an underfunded, volunteered project. See also Martin's comment https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/112#issuecomment-423617765 :-).

**Comment by nevi-me** [comment]
Honeymoon 🎆 

I understand, I had a look at the code, I'm familiar with Python, but don't yet know much about QGIS. I suppose I'm asking more from the perspective that if it's something that's not too difficult to fix, and time is the main concern, then I could take a stab at it if I had some clear direction.

By "installed at the client", do you mean the fonts existing on one's machine?

**Comment by sfkeller** [comment]
> By "installed at the client", do you mean the fonts existing on one's machine?

Yes.

**Comment by Alakalufs** [comment]
I have the same problem (look good in QGIS 2 and get "?" in QGIS 3) but I notice that the data defined properties in the styling are not the same (and they are right in QGIS 2 (the little box is yellow) but wrong in QGIS 3 (the box is red).

I think this is the source of the problem as copypasting the style between QGIS 2 and 3 solve the label problem (but the POI icon dont appear in QGIS 3)

For reference the data defined style in QGIS 2 is  `if_not_exists('c:/users/username/appdata/local/temp/vector_tiles_reader/styles/OpenMapTiles.com (default entry with credits)/icons/'+'star_11'+'.svg', 'c:/users/username/appdata/local/temp/vector_tiles_reader/styles/OpenMapTiles.com (default entry with credits)/icons/empty.svg')`

The same in QGIS 3 is :+1: 
`if_not_exists('C:/Users/USERNAME/AppData/Local/Temp/vector_tiles_reader/styles/OpenMapTiles.com (default entry with credits)/icons/'+'b'star_11''+'.svg', 'C:/Users/USERNAME/AppData/Local/Temp/vector_tiles_reader/styles/OpenMapTiles.com (default entry with credits)/icons/empty.svg')`
