### ISSUE TITLE
OSX QGIS3 OSError:  Could not find lib geos_c or load any of its variants 

### ISSUE THREAD

**Issue by citizenfish** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#212]
This error occurs after selecting an mbtiles file for viewing. Looks like a missing dependency?

Error is 

```
OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/Python.framework/Versions/3.6/lib/libgeos_c.dylib', '/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib']. 
Traceback (most recent call last):
  File "/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/vtr_plugin.py", line 379, in _on_connect
    reader = self._create_reader(connection=connection)
  File "/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/vtr_plugin.py", line 808, in _create_reader
    from .vt_reader import VtReader
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/vt_reader.py", line 35, in 
    from .util.mp_helper import decode_tile_native, decode_tile_python, can_load_lib
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/util/mp_helper.py", line 1, in 
    import mapbox_vector_tile
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs/mapbox_vector_tile/__init__.py", line 1, in 
    from . import encoder
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs/mapbox_vector_tile/encoder.py", line 4, in 
    from shapely.geometry.base import BaseGeometry
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/shapely/geometry/__init__.py", line 4, in 
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/shapely/geometry/base.py", line 17, in 
    from shapely.coords import CoordinateSequence
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/shapely/coords.py", line 8, in 
    from shapely.geos import lgeos
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/shapely/geos.py", line 111, in 
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/Python.framework/Versions/3.6/lib/libgeos_c.dylib', '/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib'].


Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.0.2-Girona Girona, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python
.
/Users/daveb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
```

**Comment by citizenfish** [comment]
Note this is easily fixed with 

```
brew install geos
```

**Comment by tomchadwin** [comment]
I thought geos was a QGIS dependency, so it should be installed already. I stand to be corrected, though.

**Comment by citizenfish** [comment]
It's not a mandatory you are thinking of GDAL I suspect

**Comment by tomchadwin** [comment]
No - it's there in Help > About:

```
QGIS version
3.2.2-Bonn
QGIS code revision
26842169e9
Compiled against Qt
5.9.2
Running against Qt
5.9.2
Compiled against GDAL/OGR
2.2.4
Running against GDAL/OGR
2.2.4
Compiled against GEOS
3.6.1-CAPI-1.10.1
Running against GEOS
3.6.1-CAPI-1.10.1 r0
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.1
PROJ.4 Version
493
```

Pretty sure GEOS is the underlying geometry library for QGIS. In which case, could it either be the Python bindings which have an issue, or some pathing problem which means it's looking for GEOS at a system level, not the QGIS dependency? I'm no Mac or Linux user, so this is all v woolly, and others will hopefully know better how to investigate.

**Comment by citizenfish** [comment]
I am a Mac user and on install you have to install GDAL separately not GEOS. It is more than likely the python bindings as what you are looking at are the C++ linkages.

**Comment by mnboos** [comment]
I think we can say it's a prerequisite, to have GEOS installed.

**Comment by sfkeller** [comment]
This is not a dependendy of this plugin but of QGIS. I'm sure full GEOS installation is a mandatory dependency of QGIS, since QGIS is depending on OGR, which is part of GDAL. 

See e.g. https://gis.stackexchange.com/questions/187105/instructions-for-qgis-mac-installation/240800 and https://gis.stackexchange.com/questions/246187/installing-qgis-on-mac-os-sierra-10-12-5-the-gdal-2-1-framework-is-required .

**Comment by citizenfish** [comment]
Just a comment that I am getting the same error on a fresh install of QGIS 3.10 on OSX Catalina.

QGIS runs fine, all other plugins appear to work OK

**Comment by JKMcCloskey** [comment]
Similar here @citizenfish, tried with QGIS 3.10 and 3.4 (both Long Term Releases):

The traceback includes the python path QGIS is using which includes a geos folder: 
`Python Path:
/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python
/Users/jamesmccloskey/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jamesmccloskey/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.4.app/Contents/Resources/python
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.4.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Users/jamesmccloskey/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jamesmccloskey/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs`

The geos folder contains files:
geos.py
_geos.so

But no geos_c

**Comment by GeospatialMax** [comment]
For everyone's benefit: The above solution (brew-installing geos) hasn't helped in my case. Instead the following has resolved my issues:

```
brew install geos
```
(as above to install GEOS globally on the system)

```
sudo ln -s /usr/local/Cellar/geos/3.8.1/lib /opt/local/lib
```
(this will create a soft link from one of the locations the plugin is looking for the GEOS library to where Homebrew has installed it. I didn't have the folder /opt/local, so had to create it in advance)

After this all was working fine.

**Comment by sumarlidason** [comment]
I experienced this today, fixed w/
```bash
% ln -s /Applications/QGIS3.10.app/Contents/MacOS/lib/libgeos_c.1.dylib \
  /Applications/QGIS3.10.app/Contents/MacOS/lib/libgeos_c.dylib

% ls -lhat /Applications/QGIS3.10.app/Contents/MacOS/lib/ | grep libgeos
lrwxr-xr-x    1  admin    17B Apr 21 09:27 libgeos_c.dylib -> libgeos_c.1.dylib
-rwxr-xr-x@   1  admin   192K Apr 17 15:56 libgeos_c.1.dylib
-rwxr-xr-x@   1  admin   1.3M Apr 17 15:55 libgeos-3.7.2.dylib
```
| name | version |
| --- | --- |
| QGIS version | 3.10.5-A Coruña |
| QGIS code revision | 984615fe1e |
| Compiled against Qt | 5.12.3 |
| Running against Qt | 5.12.3 |
| Compiled against GDAL/OGR | 2.4.1 |
| Running against GDAL/OGR | 2.4.1 |
| Compiled against GEOS | 3.7.2-CAPI-1.11.2 |
| Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125 |
| Compiled against SQLite | 3.28.0 |
| Running against SQLite | 3.28.0 |
| PostgreSQL Client Version | 11.3 |
| SpatiaLite Version | 4.3.0a |
| QWT Version | 6.1.4 |
| QScintilla2 Version | 2.11.1 |
| Compiled against PROJ | 5.2.0 |
| Running against PROJ | Rel. 5.2.0, September 15th, 2018 |
| OS Version | macOS 10.15 |

**Comment by DrewWeth** [comment]
Still an issue July 2020, @sumarlidason's fix worked-- I also upgraded `geos`. Thanks!

**Comment by timmeko** [comment]
Still an issue in Aug 2020. @sumarlidason's fix worked for me also after much head-to-desk-banging in the past couple days. Thank you!

**Comment by sfkeller** [comment]
Sorry for this inconvenience. 

IMHO Apple seems to have much fun playing around with distros with unanounced changing libraries...

In any case: Pls. be aware that the reason and motivation to maintain this plugin has siginificantly decreased after Vector Tiles support is built-in and written in C++ since newest QGIS versions.
