### ISSUE TITLE
OpenMapTiles connections broken

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#227]
The predefined OMT connections don't work anymore, only a HTTP status 201 is returned.

@klokan Did you change something on your infrastructure?

**Comment by petrsloup** [comment]
What URLs do you use at the moment? All legacy endpoints should return standard 301 (redirect) status code.

**Comment by mnboos** [comment]
The urls look like this:

```
https://maps.tilehosting.com/data/v3/7/64/64.pbf?key=...
```

The key is replaced by the real one. In Postman and in the browser these requests go through without any problems.

**Comment by mnboos** [comment]
Fixed. Master branches (i.e. deployments) were not affected.
