### ISSUE TITLE
Improve the OpenMapTiles default styling

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#23]
Some default styles for OpenMapTiles sources are delivered with the plugin. However, some (important) styles are missing and other should be improved.

- Improve crossing/ending roads
- Assure svg-Markers are working (hardcoded svg paths) (e.g. helipad)

**Comment by mnboos** [comment]
I'm currently using absolute paths to svg icons for my styles. Obviously that's only working on my local machine. I'd rather use paths relative to the plugin directory. Does any of you @sfkeller and @tomchadwin know, how this can be done?

One option would be, to modify the style qml file during runtime and replacing the hardcoded path (respectivly a substitute like {iconspath}) with the actual path of the current system.

**Comment by mnboos** [comment]
Solved.

I "calculate" the path for a specific POI (e.g. 'restaurant' or 'ferry_terminal') in the code and assign it to the feature as attribute. This way the style is as clean as possible and I've got the possibility to add additional logic when creating the path.

**Comment by tomchadwin** [comment]
Can you point me towards the specific code which does this?

**Comment by mnboos** [comment]
Here you go (function '_get_icon_path'): https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/master/vt_reader.py#L442

**Comment by tomchadwin** [comment]
Looks good. Just not sure about assigning the path as a feature attribute. You'd be better off defining a QGIS style. Where's that code?

**Comment by mnboos** [comment]
The QGIS styles are predefined in the folder 'styles'
What do you mean by 'posh'?

**Comment by tomchadwin** [comment]
#damnyouautocorrect

"path"

**Comment by sfkeller** [comment]
@mnboos Just to be sure: In menu "Settings > Options" dialog, in Tab "System", there "SVG paths" where QGIS searches for a SVG symbol. There's a default path I think "C:/Users/sfkeller/.qgis2//svg/" (weird double slash...). This allosw users to organize an arbitrary place where they maintain SVG symbols.

Your solution to bundle it with your plugin sounds reasonable. Actually, you could update this system "SVG paths", but I'm not sure what this implies.

Just to complete the list of possibilities: There's a resource sharing plugin http://plugins.qgis.org/plugins/qgis_resource_sharing/ but which is not yet widely adopted.

**Comment by sfkeller** [comment]
I just tested version 0.7. Looks good - but styling still needs some enhancement. 
Take OSM Standard Style (OSM Default Style) as a benchmark. You can visually compare with OSM Standard simply by loading the raster tiles using QuickMapServices plugin.
I mainly see that place labels are missing and primary/secondary roads should be shown much with broader width and with double-lines.
Then in the "poi*14" layer I see "?" which indicates that the marker symbols are missing.

**Comment by mnboos** [comment]
**TODO**
* The absolute paths must be removed from the features. Use relative paths.
* Rename "_svgPath" to "_symbol"
* Add svg path to QGIS
* Edit style for "place" to show label instead of point

**Comment by mnboos** [comment]
QGIS restart is required after adding custom svg-path in the options

**Comment by sfkeller** [comment]
Two style enhancements:
* Max. Scale-based visibility of labels (like housenumber) should be 5001 (not 5000).
* Color of housenumber labels should be black (not the same grey as buildings).

**Comment by mnboos** [comment]
Another enhancement to be done:
using the "rank" attribute to define which features shall be priorized at a certain zoom level.

edit: I don't know if this is even possible just with a QGIS expression.

**Comment by mnboos** [comment]
@sfkeller The two enhancements are now implemented.
