### ISSUE TITLE
SyntaxError when loading the plugin

### ISSUE THREAD

**Issue by thriskel** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#233]
Installed the plugin and while it was trying to load it gave this error:

```
Couldn't load plugin 'vector_tiles_reader' due to an error when calling its classFactory() method 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/thrizon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/__init__.py", line 25, in classFactory
    from .plugin.vtr_plugin import VtrPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/thrizon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/plugin/vtr_plugin.py", line 104
    plugin_version = f" {version}" if version else ""
                                 ^
SyntaxError: invalid syntax


Python version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516] 
QGIS version: 3.4.4-Madeira Madeira, 31adb15 
```

**Comment by mnboos** [comment]
Thanks for reporting this error! I wasn't fully aware, that this formatting functionatliy from Python is available only for Python >= 3.6.

Could you try upgrading QGIS? The latest  version should come with a newer version of Python.

**Comment by thriskel** [comment]
I tried to upgrade qgis to 3.6 but it doesn't get pass v3.4, I tried changing the repos to nightly but that didn't work either so IAM Guessing I will have to compile it, Right?

**Comment by mnboos** [comment]
Which Linux distribution are you using?

Did you follow this guide: https://www.qgis.org/de/site/forusers/download.html#linux ?

**Comment by thriskel** [comment]
Yes I used that which basically tells me to add the repo to the sources and the key, I am using Debian Stretch

**Comment by mnboos** [comment]
Then you'll have to wait for the next release (which I'm currently preparing), sorry.

**Comment by thriskel** [comment]
It's ok, thank you for your time 😊
