### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#24]
The user experience is sometimes a bit bumpy and this needs to be improved.

**Comment by sfkeller** [comment]
When opening a Vector Tiles Server Layer (especiall when mergin tiles etc.) there's a small progress dialog and there are also blue info text showing up: Pls. check all infos to reduce duplication and confusion of the user. And these log infos should be consistent between adding Vector Tiles from file or server.

**Comment by mnboos** [comment]
@sfkeller The blue info text comes from a QGIS algorithm that I cannot disable.
