### ISSUE TITLE
Open custom MVT URL

### ISSUE THREAD

**Issue by drnextgis** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#243]
Is it possible to open custom URL `http://...?x={x}&y={y}&z={z}.pbf`  with that plugin? Maybe I misunderstood the purpose of the plugin but didn't find a way how to do it. If it is required to create a local file for that - no problem.

**Comment by mnboos** [comment]
If it's serving Mapbox Vector Tiles, it should be possible by creating a local TileJSON file with content similar to: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/files/3269379/arcgis_tilejson.json.txt

Just replace the URL and the layers. The layers are required to build the node tree within QGIS, or in other words, at least the names (i.e. "id" property) are required.

You can then connect to it like described here: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/170#issuecomment-501120332

**Comment by drnextgis** [comment]
Thanks for quick reply. It is working now. I was a little bit confused that there is no "open" button next to "TileJSON URL" field. Also it is not obvious that it is possible to put the local file path in that field. I've discovered some other issues but it is for another ticket.
