### ISSUE TITLE
Create Help / Documentation

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#25]
With an increasing number of features and options, I think there's a necessity for a) a documentation and b) a user guide.

**Comment by mnboos** [comment]
@sfkeller Have a look at the userguide (https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/wiki/User-Guide). Is there something missing or can I improve something?

**Comment by sfkeller** [comment]
Looks good so far! A user guide for such a plugin doesn't need to be long.

**Comment by sfkeller** [comment]
Just don't forget to mention the sample data file and predefined service(s). 
And of course documentation (= update) is a continuous (periodic) task.

**Comment by mnboos** [comment]
User guide updated:
- **Clear Cache** mentioned
- Export explained

**Comment by sfkeller** [comment]
I have updated GISWiki website: https://giswiki.hsr.ch/Vector_Tiles_Reader_QGIS_Plugin
