### ISSUE TITLE
Native decoding - sometimes supported, sometimes not

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#259]
Sometimes the VTR log tells me that native decoding is supported, and sometimes it tells me it is not:

```
2019-10-03T09:29:49     WARNING    Native decoding supported!!! (Windows, 64bit)
```
```
2019-10-03T09:51:34     WARNING    Native decoding not supported. (Windows, 64bit)
```

Could the test mechanism be unreliable in any way?

**Comment by mnboos** [comment]
That's actually surprising. I would have thought, it's reliable in a sense, that it always either works or not but not, that it sometimes does and sometimes not on the same machine in the same environment.

**Comment by tomchadwin** [comment]
OK. Can you think of any manual checks I can do on my system to see whether I can find the issue? Will do some more investigation to see if any pattern for success/failure is apparent.

**Comment by tomchadwin** [comment]
How about this:

1. Open QGIS
2. Connect to a remote VT source and add layers
3. "Native decoding supported"
4. New QGIS project (discard changes)
5. Connect to same remote VT source and add same layers
6. "Native decoding not supported"

Can you recreate?

**Comment by tomchadwin** [comment]
It seems that after `mp_helper.unload_lib()` is called, `_native_lib_handle` is never reset. I guess this is because it only runs when `mp_helper` is imported, as it's not within any function/class def? Let me see if I can see where one could try to move it to see whether it might work.
