### ISSUE TITLE
Implement caching (big final sprint of PA1)

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#26]
The performance of the plugin could be improved with a caching mechanism.

**Comment by sfkeller** [comment]
That could be an issue big enough (indeed) for a final sprint.

**Comment by tomchadwin** [comment]
Agreed. Caching is one of the hardest things to design and implement successfully.

**Comment by sfkeller** [comment]
Yes. Motto is "Make it right before making it faster" :-)

**Comment by mnboos** [comment]
I implemented some caching:

Loaded and decoded tiles will be cached (in a temp directory). This already improves the loading performance significant. 
Additionally, I could also cache the GeoJSON features but I'm not sure if that's really necessary.
