### ISSUE TITLE
Duplicate name display at different zoom levels

### ISSUE THREAD

**Issue by ChameleonScales** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#262]
I tried using templates from [MapTiler](https://www.maptiler.com/) and at least one of them ([Voyager](https://cloud.maptiler.com/maps/voyager/)) has name display issues at different zoom levels. More precisely, place names can appear in double, triple or even quadruple at some zoom levels in QGIS, even though they don't on MaptTiler (as you can see from the above Voyager link).
I use QGIS 3.8 flatpak on Debian 10 and use the free MapTiler plan (so I only have the vector option)
I contacted the Maptiler support about this but they recommended me to file an issue here.

**Comment by mnboos** [comment]
That's because the style converter is to be considered experimental. The Mapbox style specification is to complex and fast changing in order for me to maintain a stable and reliable converter.
