### ISSUE TITLE
Refresh of Style

### ISSUE THREAD

**Issue by frodrigo** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#274]
The Style I'm using is updated on the server but the plugin does not refresh it. I not found how to force a style refresh.

**Comment by mnboos** [comment]
Hi

When does the style get updated on the server? During runtime of the plugin? Currently the styles are only converted, when a connection is loaded (i.e. if you click "Add" on the connections dialog and the layers get added to the view).

**Comment by frodrigo** [comment]
Thank. Ok. I was in trouble because I was not using the connection tab, but the mbtiles. And even on QGis restart it does not read the style from the server.
