### ISSUE TITLE
Tiles never loaded when tiles aren't included in the map extent.

### ISSUE THREAD

**Issue by Kanahiro** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#276]
When you add a MVT layer and the MVT layer area is out of the map extent, no vector is loaded or reloaded even if the extent changed to area including MVT.
If MVT layer area are enoughly wide like preset 'MapTiler Cloud', no any trouble are but all MVT layers are not wide like that.
In particular, just after open QGIS GUI no layer added on a map, this problem will occur because the map extent don't always include MVT layer for adding.
When the map extent are out of a MVT layer area, no tile will be loaded. It's good but, even when the extent is changed to include MVT layer, no tile won't be reloaded.

 I want to improve and now try to fix this by reading codes.
Please advise me.

**Comment by mnboos** [comment]
Hi and thanks for your request!

It is by design, that data is only loaded, if it's in the current extent. But it seems to be an error, that even upon reload, it is not actually loaded.

If the datasource is under your control, you could maybe fix it by setting the extent in the metadata, the plugin would then know what to load initially.

**Comment by Kanahiro** [comment]
Thanks your comment.
However,  it's metadata cannot be edited because a datasource is provided by MapTiler.jp.

Now I found some codes cause this problem.
in vtr_plugin.py, 756
```python
if not is_add and not self._get_all_own_layers():
        info("Loading aborted as there are no layers of the current connection already loaded.")
        return
#layer loading process following
```

<S>
is_add means that function is called by _on_add_layer().
self._get_all_own_layers() is layers loaded from Vector Tile Source.

This means, if no layers are found when FIRST loading, layer loading processes never run second or more.
Based on the above, I will suggest to remove that codes, if no importance is in that codes.
I send a pull request regarding this. Thanks.
</s>

These codes occur the problem but removing them occurs another problem. Even when you remove vector tile layers, reloading them will not stop until close QGIS.
Sorry for confusing and I retry fix this.
