### ISSUE TITLE
Improve CRS handling

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#28]
Currently the plugin expects sources with EPSG:3857. If that's not the case, there might be some problems. This has to be tested and improved. However, the problem is still the availability of test data sources.

**Comment by sfkeller** [comment]
Related to #22 ?

**Comment by sfkeller** [comment]
> However, the problem is still the availability of test-datasources.

Waiting for data source from Klokan.

**Comment by mnboos** [comment]
Good news: Was able to test with t-rex and it worked!

**Comment by mnboos** [comment]
Tested with a EPSG:21781 source and worked after small changes.
