### ISSUE TITLE
Dedup/aggregate objects occuring in VT up to 4x within buffer outside grid

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#29]
Looking at „Fäschtinseli“ (near HSR) this named object occurs 3x in the final QGIS layer. The screenshot below shows 3x for island name and 3x for bbq place [1].

This should be deduplicated and eventually aggregated into an multi-valued field.

The reason for this duplication may be that VT generators apply a „buffer_size“ which is quite large (up to 254 units) for POIs/labels. See also MB VT spec. and [2].

[1] OSM http://www.openstreetmap.org/node/392055782 and http://www.openstreetmap.org/way/34174216
[2] buffer_size https://github.com/openmaptiles/openmaptiles/blob/e8155bff961f2287e9d06a69ea19ce68e664aa8b/layers/place/place.yaml 

![grafik](https://cloud.githubusercontent.com/assets/43340/25377384/9e525e06-29a7-11e7-8d3e-9dde83d95554.png)

**Comment by mnboos** [comment]
@sfkeller Do you think it's enough to assure the poi names are unique or should I allow duplicated poi names if there are NOT on the same or neighbouring tiles?

**Comment by sfkeller** [comment]
The higher goal is "simply" to recreate the same OSM object. So, if there have been two OSM objects in the original OSM database (as it's the case with "Fäschtinseli" as there is one island way and a bbq node inside/nearby with same name), I'd expect to get two objects back in the QGIS layer after decoding a VT source (unless the VT generator did some processing before he encoded it in which case it's impossible to recreate the original OSM objects). 

So, to answer your question: Don't "deduplicate" just based on same name and vicinity. Just deduplicate if the e.g. have the same name *and* the same geometry.

**Comment by mnboos** [comment]
By "same geometry" you mean the geometry type (point, linestring, polygon) or the geometry itself, i.e. the coordinates (not the location) of the feature?

**Comment by mnboos** [comment]
Done. @sfkeller please make a short test if it works as you expect.
