### ISSUE TITLE
the plugin craches the qgis program

### ISSUE THREAD

**Issue by smounir** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#290]
Hello, I have tried many times, Once the plugin installed it crashes the qgis program.
QGIS Version 3.26.3-Buenos Aires

**Comment by sfkeller** [comment]
Pls. note that the "Vector-Tiles-Reader-QGIS-Plugin" has been superseeded since QGIS 3.14 version by a native support for loading of vector tiles (MBVT); see e.g. https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector_tiles/vector_tiles_properties.html
