### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by Murthy10** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#3]
I recommend you to enhance your .gitignore file with this template:
https://github.com/github/gitignore/blob/master/Python.gitignore

Add don't add IDE specific files to the repository, it's often a good idea to use a global .gitignore for this.
`git config --global core.excludesfile $HOME/.gitignore `

After this command you could add vs code specific records in your global gitignore file.
https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore

**Comment by mnboos** [comment]
Thanks, I appreciate the feedback and did what you suggested.
