### ISSUE TITLE
Add layer gone?

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#30]
I feel rather stupid, but I've just upgraded to 0.6.1, and I now don't know how to use the plugin. The only option in `Plugins > Vector Tiles Reader` is `About`. How do I import a VT mbtiles file?

**Comment by sfkeller** [comment]
Good question: Menu entries should be enhanced.

See the icon from "Add a Vector Tile Layer" in the Layers Toolbar (mostly to the left).

Anyway see https://giswiki.hsr.ch/Vector_Tiles_Reader_QGIS_Plugin#How_to_Add_a_Vector_Tile_Layer (just updated).

Perhaps @mnboos can enhance the plugin and the wiki help page.

**Comment by tomchadwin** [comment]
Urgh. Sorry not to have found that menu item. Thanks.

**Comment by tomchadwin** [comment]
So I added a local layer fine, but I don't understand the instructions on that page for a tileserver:

> Go to menu "Add Tile Server Layer..."

Which menu? Where?

**Comment by sfkeller** [comment]
Currently the menu is gone. 
I meant the icon in the Layers Toolbar.
The menu item should show up again under "Layer > Add Layer..." and probably under "Vector".

**Comment by tomchadwin** [comment]
Got it. Apologies again.
