### ISSUE TITLE
Dialog cancel button leaves layer group

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#31]
1. Add mbtiles local vector tile layer
2. Click cancel in progress dialog

An empty layer group with the name of the mbtiles file remains in the QGIS layers list.

**Comment by mnboos** [comment]
Done

**Comment by tomchadwin** [comment]
The cancel behaviour seems to have changed, but it probably fine. The layers created so far remain. Is that the best approach, or should they be deleted?

**Comment by mnboos** [comment]
IMHO is that okay. I already like this behaviour as I can decide spontaneously to cancel the loading process but nevertheless have some data to work with.

**Comment by tomchadwin** [comment]
Agreed. Simple to delete the root layer group if you want to revert. Thanks.
