### ISSUE TITLE
Implement free default Vector Tile Server connection in Add Layer dialog

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#32]
The dialog "Add Layer(s) from a Vector Tile Server" currently initially has no entries. It would be convenient for new users to have a default entry. Klokan offers such a free access given the API key is not shown. So, I'd suggest to add a default entry e.g. 

Name: OpenMapTiles (don't change TileJSON URL; get you own key from openmaptiles.com/hosting/)
TileJSON URL: http://free.tilehosting.com/data/v3.json )

In the code, the API key - which has to be communicated to Klokan before - is added to the TileJSON URL, so that users don't see it.

In the help (built-in dialog? http://giswiki.hsr.ch ) I suggest that there's an explanation that users can get an own key at https://openmaptiles.com/hosting/ .

Don't forget to mention the license and attribution (=> "© Klokan Technologies CC-BY, © OpenStreetMap contributors") in the QGIS layer properties, and in the help (http://giswiki.hsr.ch ).

**Comment by sfkeller** [comment]
Related to #27 .

**Comment by mnboos** [comment]
See the area "Attribution", is that okay?

![image](https://cloud.githubusercontent.com/assets/22575883/25522862/c637ba06-2c04-11e7-9f81-c8a585b4f2bd.png)

**Comment by sfkeller** [comment]
Almost :-) Set 
```
Attribution
Title: Vector Tiles © Klokan Technologies GmbH (CC-BY), Data © OpenStreetMap contributors (ODbL)
URL: https://openmaptiles.com/hosting/
```

And what about theses metadata sections?
```
Description
Short name: ???
Title: ???
...
MetadataUrl
Url: https://openmaptiles.org/schema/

```

**Comment by mnboos** [comment]
Okay I've changed the attribution.

For the other metadata I've added issue #35
