### ISSUE TITLE
Refactor directory and filenames to lowercase and underscore instead spaces

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#34]
The plugin dir "Vector-Tiles-Reader-QGIS-Plugin" (under %userprofile%/.qgis2/python/plugins/ ) should be renamed to "vector-tiles-reader" (if possible); and the "sample data" to "sample_data".

**Comment by mnboos** [comment]
I renamed sample_data.

To be able to rename the directory name, I assume I'll have to delete all old versions and then add the latest one. When I tried to upload the zip with another foldername, it has been declined because the folder name was not the same as in the uploads before.

**Comment by tomchadwin** [comment]
The root folder in the zip must have the same name. You can't change a plugin name in the QGIS plugins repo. It's been asked before, and it's simply not supported. You would have to delete the existing plugin and upload a new one with the new name.

**Comment by mnboos** [comment]
I don't want to rename the plugin in the repo, just the folder that is created under "%userprofile%/.qgis2/python/plugins/"

**Comment by sfkeller** [comment]
OK.

**Comment by mnboos** [comment]
Ok what?

**Comment by sfkeller** [comment]
Do what's possible. I'm OK not to rename the plugin in the repo but just the folder.

**Comment by tomchadwin** [comment]
Since you are still early and experimental, I'd consider making a considered decision on the plugin name, and getting folder and plugin name in sync, by deleting the existing plugin from the repo if necessary. Everything is then consistent going forwards. Apologies for intruding on the discussion.

**Comment by mnboos** [comment]
No need to apologize. I'm happy and appreciate all feedback.

So I think I should delete and re-add the plugin with a proper folder and plugin name before the next release.

@sfkeller the plugin name "Vector Tiles Reader" is still okay?
@tomchadwin Am I right with the assumption, that the link to the plugin contains the name of the plugin folder in the zip?

**Comment by tomchadwin** [comment]
@mnboos Which link to the plugin?

**Comment by mnboos** [comment]
The one in the QGIS plugin repo:
http://plugins.qgis.org/plugins/Vector-Tiles-Reader-QGIS-Plugin/

**Comment by sfkeller** [comment]
Plugin name "Vector Tiles Reader" is still okay. This still means that I'd like to speak as "Vector Tiles Reader" QGIS Plugin if needed, and that's the reason why https://giswiki.hsr.ch/Vector_Tiles_Reader_QGIS_Plugin is still valid to me.

**Comment by mnboos** [comment]
Okay, that means the new naming would be:
Plugin name in QGIS repository: Vector Tiles Reader
Plugin folder name: vector_tiles_reader
giswiki url wouldn't change.

**Comment by tomchadwin** [comment]
@mnboos If I understand the question correctly, and understand the plugin repo correctly, the answer is yes: for `plugins.qgis.org/plugins/plugin_name` and `.qgis2/python/plugins/plugin_name`, "plugin_name" cannot be different in each case.

**Comment by tomchadwin** [comment]
Or you could choose something more like "vt2qgis" or some such.

**Comment by mnboos** [comment]
Plugin with new name accepted: http://plugins.qgis.org/plugins/vector_tiles_reader/
