### ISSUE TITLE
Make some metadata available on each layer

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#35]
Set the metadata per layer.

![image](https://cloud.githubusercontent.com/assets/22575883/25523949/debf623c-2c08-11e7-8a76-b1122e741807.png)

**Comment by sfkeller** [comment]
See tab metadata in "Layer Properties", section "Description":
* Short name: <<the effective layer name from TileJSON file>>
* DataURL: <<the URL from from TileJSON file>> (with API key except for default data sources)>>

**Comment by mnboos** [comment]
Done
