### ISSUE TITLE
Background style in map styling of plugin

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#52]
In a map style there are several possibilities what is shown when there is no data: the blue sea style? a light grey continent style? a grey-scaled relief? a graticule or white/nothing?

In the predefined OpenMapTile style; (see also #23) there's currently white/nothing. In OpenMapTiles it's light grey continent style AFAIK (see http://maputnik.com/ ); like in Mapbox styles AFAIK. In Swiss geo.admin.ch it's a grey-scaled relief. Actually there's a background property in Mapbox GL JS (https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-background ) but this plugin only reads the TileJSON file. 

I "fear" we need an option (in "Add ... Layer" dialog or somewhere else) with a default, so the user can choose?

**Comment by mnboos** [comment]
Either an option on the dialog or we use the same color as on OpenStreetMap (due to the fact, that the predefiend OMT style is similar)

**Comment by tomchadwin** [comment]
If there's no data, shouldn't it be blank? The imported layers might have other existing layers under them in QGIS, which people would want to see through these gaps in the vector tile layer. Remember that the imported data won't necessarily always be OSM-derived, or necessarily be a base map of any kind.

**Comment by mnboos** [comment]
IMHO you're right. Another fact supporting that is, that the background color AFAIK has to be set on the QGIS project, not on a style or single layer.

**Comment by sfkeller** [comment]
@tomchadwin The VT we are speaking here are clearly focused to serve as base maps. So usually there is no or at most one other base map below. I remember well the design decision (e.g. in OpenMapTiles) to either assume that the (base map) background default style represents either sea or continent. If background is white (or transparent) then there's something missing.

You can check this by overlaying a MB VT layer (like Koh-Samui from sample_data) to OSM Default layer (e.g. from QuickMapTiles), then switch the OSM Default layer off and back on.

BTW: Comparing these two layers is good way anyway to improve the OpenMapTiles default styling #23.

**Comment by mnboos** [comment]
@sfkeller How about setting the same color as on openstreetmap as a first step? Or would you like to have different options the user can choose from?

**Comment by sfkeller** [comment]
Hmm. 
In case of option "Apply predefined OpenMapTiles style" set it to same color / style as on OpenMapTiles (OpenStreetMap) as a first step (no other option). 
Else too?

**Comment by mnboos** [comment]
Think setting it, if "Apply predefined ..." is enabled is okay. Additionally, I suggest to only set the background (i.e. the project background) only, if it's unchanged (i.e. "white").

**Comment by mnboos** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/22575883/25800050/f7773be2-33e7-11e7-8c4a-152657600004.png)
