### ISSUE TITLE
Enhance Add Layer(s) Dialog

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#54]
a. In Tile Server connection, add button "Add Default Servers2 (see also WMS/WMTS).
b. In File connection, when reopening the File Browse Dialog, keep last path location when reopening (defaul is).

**Comment by mnboos** [comment]
a) Don't see any advantage there. There's already a hardcoded default connection that cannot be removed.
b) Done

**Comment by mnboos** [comment]
@sfkeller Closing this. Feel free the reopen again.
