### ISSUE TITLE
Plugin does not take proxies into account

### ISSUE THREAD

**Issue by rduivenvoorde** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#55]
Trying to use the plugin here at an office which is behind a proxy. We need to set the proxy in QGIS to be able to retrieve data.

But looking into: 
https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/master/file_helper.py#L67
I see urllib2 is used, and while it is possible to make urllib2 aware of proxies (and preferable of the proxy settings from QGIS own settings, I think/hope the best option is to use QgsNetworkManager (which is actually a wrapper around Qt's QNetworkAccessManager... 

Taking up my QGIS-hat now: maybe start a discussion in QGIS community to create a python wrapper around the QgsNetworkManager which for example has an easier api then currently. For example it is not easy to have timeouts now etc etc. It would be better if all QGIS plugins would use this wrapper then...

And I wonder what the plan is with styling, could/can we use QGIS styling here? Sld's? Others?

**Comment by sfkeller** [comment]
@rduivenvoorde Regarding your question 
> I wonder what the plan is with styling, could/can we use QGIS styling here? Sld's? Others?
After any MB VT tiles have been loaded into a layer with this plugin, the usual QGIS styling capabilities apply.

For the built-in "predefined OpenMapTiles style" we use simply the QGIS styling classes. Here "OpenMapTiles" refers to the OpenMapTiles schema (not to be confused with the styles written in Mapbox GL JS delivered at OpenMapTiles.org). 

Regarding supporting a proxy: Thanks very much for your hint to QgsNetworkManager. We'll look at that.

Referring to your proposal to develop jointly an easier API: This is IMHO a very good proposal which we should submit also to the QGIS-dev mailing list. 

Unfortunately regarding the current implementation I have to point to the fact that this is a semester thesis project of @mnboos and as such bound to a given timeframe. So I'm sorry that @mnboos can't support this proposal (he eventually can try to replace urllib2 with QgsNetworkManager and implement proxies support though). 

As for myself I'll try to support your proposal as much as I can.

**Comment by sfkeller** [comment]
So, @mnboos : referring to the issue title, can you investigate if it's possible to use QgsNetworkManager instead of urllib2 while being able to catch timeouts (see e.g. #53 ).

**Comment by mnboos** [comment]
Sorry for the long delay. Yes, will investigate that.

**Comment by mnboos** [comment]
Notice for me: OMT default connection has to use SSL (https). Problem is: if the connection is already existing, it wont be replaced. That has to be fixed.

**Comment by mnboos** [comment]
@rduivenvoorde the plugin should now work with proxies due to the usage of QgsNetworkAccessManager. Thanks for the hint. Would it be possible for you to test the functionality by cloning the repo? It didn't release/publish it yet.

**Comment by mnboos** [comment]
@sfkeller Would it be possible for you to test if the timeout handling matches your expectations?
