### ISSUE TITLE
The "About" dialog

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#61]
The "About" dialog should also mention following: 
* This is a plugin maintained by Geometa Lab HSR 
* OSM community
* Klokan Technologies GmbH, saying "Get own free key for OpenMapTiles from https://openmaptiles.com/hosting/" (as weblink).

**Comment by mnboos** [comment]
See:

![image](https://cloud.githubusercontent.com/assets/22575883/26706646/5eaeebc4-473f-11e7-829d-61ab81f6df3d.png)
