### ISSUE TITLE
Show tile index(es) z/x/y in GUI

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#69]
That's for the inspection and debugging use case.
I don't have yet a specific proposal how the user could interact to show the info:
Show a graticule with labels indicating x/y in window by switching it on/off from a menu bar entry or icon?
Other proposals?

**Comment by mnboos** [comment]
The location of the mouse cursor is now shown as coordinates in xyz scheme in the QGIS statusbar.
