### ISSUE TITLE
Feature merging not working with a big number of tiles

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#7]
If a lot of tiles are loaded (i.e. >20), qgis sometimes crashes.

**Comment by sfkeller** [comment]
There are several approaches to handle this. In webservices like WFS or ArcGIS REST Services (see https://giswiki.hsr.ch/ArcGIS_REST_API_Connector_QGIS_Plugin ). 
A rather simple (but not so ideal) is to introduce an option/parameter (e.g. "maxTiles" or "maxFeatures"). If this limit is reached, reading process stops and issues a QGIS Warning.

**Comment by mnboos** [comment]
This problem disappeared during the improvement of the merging process.
