### ISSUE TITLE
Generated layers of geometry type Point should be Point - not MultiPoint

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#71]
All generated layers which originally are of geometry type Point should really be Point - not <<Point (WKB type: "MultiPoint")>>.
Currently all layers are MultiPoint, place, housenumber, water_name, transportation_name, poi, etc. 
This is not correct at least for some of them. 
Some algorithms and functionalities are not available for MultiPoint.
Check if this is an issue in the MVT data ecoding.

**Comment by sfkeller** [comment]
It's theoretically perhaps possible to detect point/multipoint on client side. 
But it seems to be more sensible when the data - and before also the MVT spec. - indicates it.
See https://github.com/mapbox/vector-tile-spec/issues/77

**Comment by mnboos** [comment]
It should be fixed. Points are detected correctly as Point/MultiPoint and LineStrings as well as Polygons will now always be MultiLineString/MultiPolygon.
