### ISSUE TITLE
Add custom http request headers for tilejson

### ISSUE THREAD

**Issue by nextstopsun** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#72]
Can you please add an ability to set custom http headers for tilejson url? Some servers need specific headers to return correctly formatted tilejson.

**Comment by sfkeller** [comment]
We have a code freeze now, so no promises.
Can you provide some more details (which headers?) and - most important - some servers to test?

**Comment by nextstopsun** [comment]
I'm serving tilejson via PostgREST and I need to add headers for it to work:
`Accept: application/vnd.pgrst.object+json`
`Authorization: Bearer` 
Here are some docs on this topic: https://postgrest.com/en/v4.1/api.html#singular-or-plural

I'm planning to serve tiles with postgrest too, so custom headers would be needed there also.
I guess there are other cases when custom headers should be added to properly communicate with tile server.

**Comment by sfkeller** [comment]
We're using QgsNetworkAccessManager of QGIS and thus support also Proxy configuration as they an set by the user in the QGIS menu "Settings", dialog "Options > Network". In fact there's also a User-Agent value set by user (default "Mozilla/5.0" QGIS 2.18.14).

So, in case this enhancement would be supported by the plugin, I'm not sure where to put it exactly: To the layer connection?

@mnboos : Looking at the code where QgsNetworkAccessManager is used https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/master/util/network_helper.py I saw a smell here:
`  28: req.setRawHeader('User-Agent', 'Magic Browser')
`
I agree our plugin is magic :-) but should'nt this be replaced by the User-Agent value?

**Comment by sfkeller** [comment]
@nextstopsun Is this still an issue for you? 

If yes, I'm still unsure if it makes sense to require the client - and thus to disturb the user - to set a source and vendor specific http header, when this can be resolved otherwise.

**Comment by mnboos** [comment]
> req.setRawHeader('User-Agent', 'Magic Browser')

This code has now been removed, as it became obsolete with the chame from urllib to QgsNetworkAccessManager. I think custom header shoud be set in a proxy, not in the plugin itself.

**Comment by nextstopsun** [comment]
IMHO proxy settings is a general one. The headers I've mentioned are used only for fetching vector tiles from a specific server.

**Comment by sfkeller** [comment]
Ok. So this is an possible option to be handled by the VT source layer/connection.

Initially - at the top - you wrote about setting "custom http headers for tilejson url" (not fetching tiles) and gave an example of the header you expect. 

Can you explain once again 1. which requests are affected, 2. why this can't be handled by the server, and 3. can you pls. provide some TileJSON URLs to test?
