### ISSUE TITLE
Option for base map mode where tiles are loaded according to zoom level and flushed

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#73]

**Comment by nvkelso** [comment]
Is this meant to have the same automatic move-map-plugin-updates functionality as the OSM raster map tiles plugin?

**Comment by sfkeller** [comment]
When map is moved/panned the plugin updates already the tiles and adjusts the GeoJSON cache. 
I'd rather would describe this enhancement: "flush old and load new tiles when zooming out or in", like the JS library does.

**Comment by mnboos** [comment]
@nvkelso move-map-plugin-updates functionality is now implemented and will be included in the next release.

**Comment by nvkelso** [comment]
Awesome!
