### ISSUE TITLE
Trap for single zoom (rather than default zoom range) requests

### ISSUE THREAD

**Issue by nvkelso** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#79]
When I add a single zoom (e.g. 11) instead of a range of zooms (like 11-14) I get the following error:

```
Unexpected error during logging: tuple index out of range
Original message: 'Loading extent {} for zoom level '{}' of: {}', params: '(11, u'OpenMapTiles')'
```

Everything loads correctly, it's just the Python console that logs the error.

**Comment by mnboos** [comment]
Fixed in v1.0.2 (yet to be published)
