### ISSUE TITLE
Support of different default styles per "connection" tile schema

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#80]

**Comment by nvkelso** [comment]
Background is different vector tiles have different tile data schemas so one single QML per layer (or even what layers are supported) isn't possible.

Suggest namespacing OMT into it's own dir (moving existing content in styles/ into styles/omt/) and adding a new styles/mapzen/ dir.

**Comment by mnboos** [comment]
If you provide the mapzen QML files, I can integrate them and adapt the UI.

**Comment by nvkelso** [comment]
K, I'll look at that next week :)

**Comment by mnboos** [comment]
A style can now be defined per connection.
