### ISSUE TITLE
How to accelerate loading time of vector tiles?

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#85]
* Caching? 
* Integrating "Minimal MVT decoder" (C++) as shared library (.dll / .so)?

**Comment by mnboos** [comment]
I'm currently integrating the C++ mvt decoder. Decoding will be pretty fast afterwards, compared to python decoding (620 tiles took only 22 seconds to decode on Windows, with the python version that takes roughly about a minute).

**Comment by mnboos** [comment]
The loading performance has been greatly improved by the usage of a C++ decoder. If no prebuilt library matches the current system, the decoding will be done in python for compatibility reasons.
