### ISSUE TITLE
Plan/implement porting plugin to QGIS 3.0 / Qt5 / Python 3.x

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#88]
Plan/implement porting plugin to QGIS 3.0 / Qt5 / Python 3.x.

**Comment by sfkeller** [comment]
At least do some checks if the plugin currently uses deprecated functions (and if yes, which ones, and if they already can be replaced).

**Comment by tomchadwin** [comment]
I could help with this, but I'll obviously also have to convert my plugin, so we'll see if I have time or not. I did a test run quite a few months back, and it wasn't too bad. Can you tag this issue if you create a branch purely for QGIS3 compatibility?

**Comment by mnboos** [comment]
It's already working:

![image](https://user-images.githubusercontent.com/22575883/32990570-f7434d04-cd2b-11e7-8c0e-00afa74e023a.png)

**Comment by mnboos** [comment]
See #132 

However, I'm currently letting this issue open, as QGIS is officially only at version 2.99.
