### ISSUE TITLE
Add predefined Mapzen connection

### ISSUE THREAD

**Issue by mnboos** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#90]
If @nvkelso would provide us with a Mapzen api key, we could add another predefined connection to the Mapzen server.

**Comment by mnboos** [comment]
Done thanks to @nvkelso ! Awesome!

**Comment by nvkelso** [comment]
Glad to help :)

**Comment by sfkeller** [comment]
Thanks, Nathaniel, for making Mapzen vector tiles available for this reader!

What remains to do is the map styling and we computer scientists are not so trained in that. The approach we follow is twofold: 

1. The short term and inevitable option is to let QGIS do the styling. This is what we did with OpenMapTiles schema (see the QGIS QML style files in %userprofile%/.qgis2/python/plugins/vector_tiles_reader/styles). 
=> Here a specialist like you (:-) could add QML files to style Mapzen vector tiles schema in QGIS.
2. Martin is starting now to implement a converter which translates Mapbox GL JS Styles to QML.
=> Which styling language do you prefer at Mapzen?

**Comment by nvkelso** [comment]
> 1. The short term and inevitable option is to let QGIS do the styling. This is what we did with OpenMapTiles schema (see the QGIS QML style files in %userprofile%/.qgis2/python/plugins/vector_tiles_reader/styles).
=> Here a specialist like you (:-) could add QML files to style Mapzen vector tiles schema in QGIS.

I can take a look at that. I've filed https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/101, do you want to assign it to me?

> 2. Martin is starting now to implement a converter which translates Mapbox GL JS Styles to QML.
=> Which styling language do you prefer at Mapzen?

We write our map styles at Mapzen using Tangram's YAML syntax which is similar but very different to the Mapbox GL JS styles. YAML is a superset of JSON so no biggies there, but the ideas and implementation can vary substantially.

https://mapzen.com/documentation/cartography/styles/

**Comment by mnboos** [comment]
Yes, we want and I did! Thanks a lot!

**Comment by sfkeller** [comment]
We had to remove the predefined Mapzen connection: See #78 .
