### ISSUE TITLE
svg point symbols not displayed

### ISSUE THREAD

**Issue by jachym** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#95]
Hi,

seems, that SVG symbols for POIs are not included? 

![image](https://user-images.githubusercontent.com/1460823/31841918-f676c808-b5eb-11e7-9c6d-eda63ba026ac.png)

**Comment by jachym** [comment]
Same applies for peaks

**Comment by mnboos** [comment]
The symbols are included, but currently not working. They will be working again in the next release.

**Comment by jachym** [comment]
Well, I'm using the master branch of the project - are you saying, it should work there?

**Comment by mnboos** [comment]
No, the master branch doesn't include the fix yet. You can try the cpp-pbf2geojson branch if you want. It includes the fix and the new mvt decoder, which is a lot faster. Currently, only the windows binaries are built and up to date.

**Comment by jachym** [comment]
well, the branch does not accept locally stored files - it keeps downloading from mapzen

not sure about the geojson - I believe, GeoPackage, since it can store tiles, would be more suitable format (but do not know the details).

Right now: I want to  use local file and this branch (I see, it's in master already) seems to be broken.

**Comment by mnboos** [comment]
What keeps downloading from Mapzen? Are you saying there is an infinite loop when you try to load data?

With "local file" you mean an mbtiles file? If so, please try one of the files located in the "sample_data" folder, they should be working.

**Comment by jachym** [comment]
@mnboos it seems, the plugin loads *all* data source inputs, if set, therefore, if I set input file (mbtiles downloaded from openmaptiles.org manually), it loads first mapzen resource and then it adds the local file too 

![image](https://user-images.githubusercontent.com/1460823/31895049-78885c46-b810-11e7-8f18-3660ef16bb09.png)

**Comment by jachym** [comment]
about the sample data, I would prefer, not to point to default `user/.qgis2/python/plugins/...` directory *always*, I can understand, it makes sense from testing point of view, it's annoying, when dealing with local data

```
diff --git a/file_helper.py b/file_helper.py
index e8068ab..78d2d0b 100644
--- a/file_helper.py
+++ b/file_helper.py
@@ -69,7 +69,7 @@ def cache_tile(tile, source_name):
 
 
 def get_sample_data_directory():
-    return os.path.join(get_plugin_directory(), "sample_data")
+    return os.path.join(os.path.abspath(os.curdir))
 
 
 def get_home_directory():
```

I can prepare pull request - just want to make sure, it makes sense for you too

**Comment by jachym** [comment]
@mnboos it does the same, when selecting the local default sample files 
![image](https://user-images.githubusercontent.com/1460823/31895300-249a4bfc-b811-11e7-847e-17df7170a948.png)

**Comment by mnboos** [comment]
Can you please copy the output from the log panel?

**Comment by jachym** [comment]
@mnboos this should fix it https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/pull/98

**Comment by mnboos** [comment]
I don't understand exactly what you want to change. As soon as a mbtiles file is selected in the connections dialog, the folder is remember and the dialog will open this exact same folder the next time. Is that not working for you?

**Comment by mnboos** [comment]
I created a new issue, regarding the partially broken Mbtiles connection.
