### ISSUE TITLE
Vector layer does not "change" QGIS project

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#97]
To explain: in a new QGIS project, I add a VT layer via the plugin. If I close the project, I am not prompted to save it. Does anyone confirm?

**Comment by mnboos** [comment]
I cannot reproduce that. How do you add the layer? I assume you have the latest version 1.2.0?

**Comment by sfkeller** [comment]
_(Drag & Drop of an mbtiles into the map window - as it's working e.g. with GeoPackage would be cool ;-))_

**Comment by tomchadwin** [comment]
@mnboos No, I can't recreate now, so will close. When it heppened, I loaded Mapzen, but nothing appeared on the canvas, so perhaps it was a different issue.
